# -*- coding: utf-8 -*-
"""Dl(mini proj).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IyD8jH4j02rp4PmfMrOBvlcREIp2e9Qa
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

# Enable eager execution (fixes numpy() error)
tf.config.run_functions_eagerly(True)

print(f"TensorFlow version: {tf.__version__}")
print(f"GPU Available: {tf.config.list_physical_devices('GPU')}")
print(f"Eager Execution: {tf.executing_eagerly()}")

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# =========================
# 1. LOAD & PREPARE DATA
# =========================

print("\n" + "="*70)
print("LOADING AND PREPARING DATA")
print("="*70)

features = pd.read_csv("dengue_features_train.csv")
labels = pd.read_csv("dengue_labels_train.csv")

df = pd.merge(features, labels, on=["city", "year", "weekofyear"], how="inner")
df = df.sort_values(by=["city", "year", "weekofyear"]).reset_index(drop=True)

# Focus on San Juan
df_sj = df[df["city"] == "sj"].copy().sort_values(["year", "weekofyear"]).reset_index(drop=True)

# Create date index
def create_weekly_date(df):
    df = df.copy()
    df["date"] = pd.to_datetime(
        df["year"].astype(str) + "-W" + df["weekofyear"].astype(str) + "-1",
        format="%Y-W%W-%w"
    )
    return df

df_sj = create_weekly_date(df_sj)
df_sj = df_sj.set_index("date").sort_index()

# Reindex to continuous weeks
def reindex_weekly(df):
    df = df.copy()
    df = df[~df.index.duplicated(keep="first")]
    full_range = pd.date_range(start=df.index.min(), end=df.index.max(), freq="W-MON")
    df = df.reindex(full_range)
    return df

df_sj = reindex_weekly(df_sj)
df_sj["city"] = "sj"

# Handle missing values
CLIMATE_COLS = [col for col in df_sj.columns
                if col not in ["city", "year", "weekofyear", "total_cases"]]

df_sj[CLIMATE_COLS] = df_sj[CLIMATE_COLS].interpolate(method="linear").ffill().bfill()
df_sj["total_cases"] = df_sj["total_cases"].interpolate(method="linear", limit=2)
df_sj = df_sj.dropna(subset=["total_cases"])

print(f"San Juan data shape: {df_sj.shape}")
print(f"Date range: {df_sj.index.min()} to {df_sj.index.max()}")
print(f"Cases range: {df_sj['total_cases'].min():.0f} to {df_sj['total_cases'].max():.0f}")

# =========================
# 2. ADVANCED FEATURE ENGINEERING FOR DL
# =========================

print("\n" + "="*70)
print("FEATURE ENGINEERING FOR DEEP LEARNING")
print("="*70)

def build_dl_features(df, lookback=12):
    """
    Build comprehensive features optimized for deep learning
    Includes temporal sequences for LSTM/1D-CNN
    """
    df = df.copy()

    # Temporal features
    df['year'] = df.index.year
    df['month'] = df.index.month
    df['week'] = df.index.isocalendar().week.astype(int)
    df['day_of_year'] = df.index.dayofyear

    # Cyclical encoding (critical for seasonality)
    df['sin_week'] = np.sin(2 * np.pi * df['week'] / 52)
    df['cos_week'] = np.cos(2 * np.pi * df['week'] / 52)
    df['sin_month'] = np.sin(2 * np.pi * df['month'] / 12)
    df['cos_month'] = np.cos(2 * np.pi * df['month'] / 12)

    # Case lag features (essential!)
    for lag in range(1, lookback + 1):
        df[f'cases_lag_{lag}'] = df['total_cases'].shift(lag)

    # Rolling statistics on cases
    for window in [3, 5, 7, 14]:
        df[f'cases_roll_mean_{window}'] = df['total_cases'].rolling(window).mean()
        df[f'cases_roll_std_{window}'] = df['total_cases'].rolling(window).std()
        df[f'cases_roll_max_{window}'] = df['total_cases'].rolling(window).max()

    # Exponential moving averages
    df['cases_ema_3'] = df['total_cases'].ewm(span=3).mean()
    df['cases_ema_7'] = df['total_cases'].ewm(span=7).mean()

    # Case momentum
    df['cases_pct_change'] = df['total_cases'].pct_change()
    df['cases_diff'] = df['total_cases'].diff()

    # Climate features
    key_climate = [
        'station_avg_temp_c',
        'station_precip_mm',
        'reanalysis_avg_temp_k',
        'reanalysis_precip_amt_kg_per_m2',
        'reanalysis_specific_humidity_g_per_kg',
        'reanalysis_relative_humidity_percent',
        'reanalysis_dew_point_temp_k'
    ]

    for col in key_climate:
        if col in df.columns:
            # Climate lags
            for lag in [1, 2, 3, 4]:
                df[f'{col}_lag_{lag}'] = df[col].shift(lag)

            # Rolling climate
            df[f'{col}_roll_mean_4'] = df[col].rolling(4).mean()
            df[f'{col}_diff'] = df[col].diff()

    # Temperature-precipitation interaction
    if 'station_avg_temp_c' in df.columns and 'station_precip_mm' in df.columns:
        df['temp_precip_interaction'] = df['station_avg_temp_c'] * df['station_precip_mm']
        df['temp_optimal'] = ((df['station_avg_temp_c'] - 27.5) ** 2) * -1

    # NDVI features
    if 'ndvi_ne' in df.columns:
        df['ndvi_avg'] = df[['ndvi_ne', 'ndvi_nw', 'ndvi_se', 'ndvi_sw']].mean(axis=1)
        df['ndvi_avg_lag_1'] = df['ndvi_avg'].shift(1)

    return df

df_sj_dl = build_dl_features(df_sj, lookback=12)
df_sj_dl = df_sj_dl.dropna()

print(f"After feature engineering: {df_sj_dl.shape}")
print(f"Total features: {len(df_sj_dl.columns)}")

# =========================
# 3. PREPARE SEQUENCES FOR LSTM
# =========================

print("\n" + "="*70)
print("PREPARING SEQUENCE DATA FOR LSTM")
print("="*70)

# Exclude non-feature columns
exclude_cols = ['city', 'total_cases', 'year', 'weekofyear', 'week_start_date']
feature_cols = [col for col in df_sj_dl.columns
                if col not in exclude_cols and not col.startswith('year')]

X_raw = df_sj_dl[feature_cols].values
y_raw = df_sj_dl['total_cases'].values

print(f"Raw feature shape: {X_raw.shape}")
print(f"Raw target shape: {y_raw.shape}")

# =========================
# 3.5. CLEAN FEATURES (FIX INFINITY/NAN)
# =========================

print("\n" + "="*70)
print("CLEANING FEATURES")
print("="*70)

# Check for problems
print(f"\nBefore cleaning:")
print(f"  NaN values: {np.isnan(X_raw).sum()}")
print(f"  Inf values: {np.isinf(X_raw).sum()}")

# Replace infinity with NaN
X_raw = np.where(np.isinf(X_raw), np.nan, X_raw)

# Fill NaN with column-wise median (more robust than mean)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')
X_raw = imputer.fit_transform(X_raw)

# Final check
print(f"\nAfter cleaning:")
print(f"  NaN values: {np.isnan(X_raw).sum()}")
print(f"  Inf values: {np.isinf(X_raw).sum()}")
print("="*70)

# =========================
# 4. SCALING (CRITICAL FOR DL!)
# =========================

# Use robust scaling for features
scaler_X = StandardScaler()
X_scaled = scaler_X.fit_transform(X_raw)

# Use MinMaxScaler for target (helps with training stability)
scaler_y = MinMaxScaler(feature_range=(0, 1))
y_scaled = scaler_y.fit_transform(y_raw.reshape(-1, 1)).flatten()

print(f"\nScaled X range: [{X_scaled.min():.2f}, {X_scaled.max():.2f}]")
print(f"Scaled y range: [{y_scaled.min():.2f}, {y_scaled.max():.2f}]")

# =========================
# 5. CREATE SEQUENCES FOR LSTM
# =========================

def create_sequences(X, y, seq_length=8):
    """
    Create sequences for LSTM
    seq_length: number of time steps to look back
    """
    X_seq, y_seq = [], []

    for i in range(seq_length, len(X)):
        X_seq.append(X[i-seq_length:i])
        y_seq.append(y[i])

    return np.array(X_seq), np.array(y_seq)

SEQ_LENGTH = 8  # Look back 8 weeks

X_seq, y_seq = create_sequences(X_scaled, y_scaled, seq_length=SEQ_LENGTH)

print(f"\nSequence shape: {X_seq.shape}")
print(f"Target shape: {y_seq.shape}")

# 6. TRAIN/VALIDATION SPLIT
# =========================

VAL_H = 52

X_train = X_seq[:-VAL_H]
X_val = X_seq[-VAL_H:]
y_train = y_seq[:-VAL_H]
y_val = y_seq[-VAL_H:]

print(f"\nTraining set: {X_train.shape}")
print(f"Validation set: {X_val.shape}")

# =========================
# 7. DATA AUGMENTATION FOR SMALL DATASETS
# =========================

def augment_data(X, y, noise_level=0.02):
    """
    Add Gaussian noise to increase dataset size
    """
    X_aug = X + np.random.normal(0, noise_level, X.shape)
    return X_aug, y

# Augment training data (double the dataset)
X_train_aug, y_train_aug = augment_data(X_train, y_train)
X_train_combined = np.vstack([X_train, X_train_aug])
y_train_combined = np.hstack([y_train, y_train_aug])

print(f"\nAugmented training set: {X_train_combined.shape}")

# =========================
# 8. BUILD DEEP LEARNING MODELS
# =========================

print("\n" + "="*70)
print("BUILDING DEEP LEARNING MODELS")
print("="*70)

# Model 1: LSTM with Attention
def build_lstm_attention(input_shape, dropout=0.3, l2_reg=0.001):
    """
    LSTM with self-attention mechanism
    Best for capturing long-term dependencies in time series
    """
    inputs = layers.Input(shape=input_shape)

    # LSTM layers with dropout
    lstm1 = layers.LSTM(128, return_sequences=True,
                        kernel_regularizer=regularizers.l2(l2_reg))(inputs)
    lstm1 = layers.Dropout(dropout)(lstm1)
    lstm1 = layers.LayerNormalization()(lstm1)

    lstm2 = layers.LSTM(64, return_sequences=True,
                        kernel_regularizer=regularizers.l2(l2_reg))(lstm1)
    lstm2 = layers.Dropout(dropout)(lstm2)
    lstm2 = layers.LayerNormalization()(lstm2)

    # Attention mechanism
    attention = layers.MultiHeadAttention(num_heads=4, key_dim=16)(lstm2, lstm2)
    attention = layers.Dropout(dropout)(attention)

    # Global pooling
    avg_pool = layers.GlobalAveragePooling1D()(attention)
    max_pool = layers.GlobalMaxPooling1D()(attention)
    concat = layers.Concatenate()([avg_pool, max_pool])

    # Dense layers
    dense1 = layers.Dense(64, activation='relu',
                         kernel_regularizer=regularizers.l2(l2_reg))(concat)
    dense1 = layers.Dropout(dropout)(dense1)
    dense1 = layers.LayerNormalization()(dense1)

    dense2 = layers.Dense(32, activation='relu',
                         kernel_regularizer=regularizers.l2(l2_reg))(dense1)
    dense2 = layers.Dropout(dropout)(dense2)

    # Output
    outputs = layers.Dense(1, activation='sigmoid')(dense2)

    model = keras.Model(inputs=inputs, outputs=outputs)
    return model

# Model 2: 1D CNN-LSTM Hybrid
def build_cnn_lstm(input_shape, dropout=0.3, l2_reg=0.001):
    """
    CNN for feature extraction + LSTM for temporal patterns
    Good for capturing both local and global patterns
    """
    inputs = layers.Input(shape=input_shape)

    # 1D CNN layers
    conv1 = layers.Conv1D(64, kernel_size=3, activation='relu', padding='same',
                         kernel_regularizer=regularizers.l2(l2_reg))(inputs)
    conv1 = layers.BatchNormalization()(conv1)
    conv1 = layers.Dropout(dropout)(conv1)

    conv2 = layers.Conv1D(32, kernel_size=3, activation='relu', padding='same',
                         kernel_regularizer=regularizers.l2(l2_reg))(conv1)
    conv2 = layers.BatchNormalization()(conv2)
    conv2 = layers.Dropout(dropout)(conv2)

    # LSTM layers
    lstm = layers.LSTM(64, return_sequences=False,
                      kernel_regularizer=regularizers.l2(l2_reg))(conv2)
    lstm = layers.Dropout(dropout)(lstm)

    # Dense layers
    dense = layers.Dense(32, activation='relu',
                        kernel_regularizer=regularizers.l2(l2_reg))(lstm)
    dense = layers.Dropout(dropout)(dense)

    # Output
    outputs = layers.Dense(1, activation='sigmoid')(dense)

    model = keras.Model(inputs=inputs, outputs=outputs)
    return model

# Model 3: Bidirectional LSTM (Best for small datasets)
def build_bilstm(input_shape, dropout=0.3, l2_reg=0.001):
    """
    Bidirectional LSTM - processes sequences forward and backward
    Excellent for small datasets with strong temporal patterns
    """
    inputs = layers.Input(shape=input_shape)

    # Bidirectional LSTM layers
    bilstm1 = layers.Bidirectional(
        layers.LSTM(64, return_sequences=True,
                   kernel_regularizer=regularizers.l2(l2_reg))
    )(inputs)
    bilstm1 = layers.Dropout(dropout)(bilstm1)
    bilstm1 = layers.LayerNormalization()(bilstm1)

    bilstm2 = layers.Bidirectional(
        layers.LSTM(32, return_sequences=False,
                   kernel_regularizer=regularizers.l2(l2_reg))
    )(bilstm1)
    bilstm2 = layers.Dropout(dropout)(bilstm2)

    # Dense layers
    dense1 = layers.Dense(32, activation='relu',
                         kernel_regularizer=regularizers.l2(l2_reg))(bilstm2)
    dense1 = layers.Dropout(dropout)(dense1)

    dense2 = layers.Dense(16, activation='relu',
                         kernel_regularizer=regularizers.l2(l2_reg))(dense1)
    dense2 = layers.Dropout(dropout)(dense2)

    # Output
    outputs = layers.Dense(1, activation='sigmoid')(dense2)

    model = keras.Model(inputs=inputs, outputs=outputs)
    return model

# Model 4: Transformer-based (Transfer Learning Approach)
def build_transformer(input_shape, dropout=0.3, l2_reg=0.001):
    """
    Transformer encoder for time series
    Uses self-attention across entire sequence
    """
    inputs = layers.Input(shape=input_shape)

    # Positional encoding
    positions = tf.range(start=0, limit=input_shape[0], delta=1)
    position_embedding = layers.Embedding(input_dim=input_shape[0],
                                         output_dim=input_shape[1])(positions)
    x = inputs + position_embedding

    # Transformer block 1
    attention1 = layers.MultiHeadAttention(num_heads=4, key_dim=32)(x, x)
    attention1 = layers.Dropout(dropout)(attention1)
    x1 = layers.Add()([x, attention1])
    x1 = layers.LayerNormalization()(x1)

    # Feed-forward network
    ffn = layers.Dense(128, activation='relu',
                      kernel_regularizer=regularizers.l2(l2_reg))(x1)
    ffn = layers.Dropout(dropout)(ffn)
    ffn = layers.Dense(input_shape[1],
                      kernel_regularizer=regularizers.l2(l2_reg))(ffn)
    x2 = layers.Add()([x1, ffn])
    x2 = layers.LayerNormalization()(x2)

    # Global pooling
    pooled = layers.GlobalAveragePooling1D()(x2)

    # Dense layers
    dense = layers.Dense(64, activation='relu',
                        kernel_regularizer=regularizers.l2(l2_reg))(pooled)
    dense = layers.Dropout(dropout)(dense)

    # Output
    outputs = layers.Dense(1, activation='sigmoid')(dense)

    model = keras.Model(inputs=inputs, outputs=outputs)
    return model

# Build all models
input_shape = (X_train.shape[1], X_train.shape[2])
print(f"Input shape: {input_shape}")

models = {
    'LSTM-Attention': build_lstm_attention(input_shape, dropout=0.4),
    'CNN-LSTM': build_cnn_lstm(input_shape, dropout=0.4),
    'BiLSTM': build_bilstm(input_shape, dropout=0.4),
    'Transformer': build_transformer(input_shape, dropout=0.4)
}

# Print confirmation
print("\n✓ Model Building Complete:")
for name, model in models.items():
    total_params = model.count_params()
    print(f"  • {name}: {total_params:,} parameters")

print(f"\nTotal models ready for training: {len(models)}")
print("="*70)

# =========================
# TRAIN MODELS SEPARATELY
# =========================

print("\n" + "="*70)
print("TRAINING DEEP LEARNING MODELS - ONE AT A TIME")
print("="*70)

input_shape = (X_train.shape[1], X_train.shape[2])
print(f"Input shape: {input_shape}\n")

# Callbacks
early_stop = EarlyStopping(monitor='val_loss', patience=15,
                          restore_best_weights=True, verbose=1)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=8,
                             min_lr=1e-7, verbose=1)

# Training config
EPOCHS = 80
BATCH_SIZE = 32
OPTIMIZER = keras.optimizers.Adam(learning_rate=0.002)

results = {}
# =========================
# MODEL 3: BiLSTM
# =========================
print("\n" + "="*70)
print("TRAINING MODEL 3/4: BiLSTM")
print("="*70)

model_bilstm = build_bilstm(input_shape, dropout=0.4)
model_bilstm.compile(optimizer=OPTIMIZER, loss='mse', metrics=['mae'])

history_bilstm = model_bilstm.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

# Predictions
y_pred_train = model_bilstm.predict(X_train, verbose=0).flatten()
y_pred_val = model_bilstm.predict(X_val, verbose=0).flatten()

# Inverse transform
y_pred_train_orig = scaler_y.inverse_transform(y_pred_train.reshape(-1, 1)).flatten()
y_pred_val_orig = scaler_y.inverse_transform(y_pred_val.reshape(-1, 1)).flatten()
y_train_orig = scaler_y.inverse_transform(y_train.reshape(-1, 1)).flatten()
y_val_orig = scaler_y.inverse_transform(y_val.reshape(-1, 1)).flatten()

# Metrics
mae_train = mean_absolute_error(y_train_orig, y_pred_train_orig)
mae_val = mean_absolute_error(y_val_orig, y_pred_val_orig)
rmse_val = np.sqrt(mean_squared_error(y_val_orig, y_pred_val_orig))
r2_val = r2_score(y_val_orig, y_pred_val_orig)
mape_val = np.mean(np.abs((y_val_orig - y_pred_val_orig) / (y_val_orig + 1))) * 100

results['BiLSTM'] = {
    'model': model_bilstm,
    'history': history_bilstm,
    'y_pred_val': y_pred_val_orig,
    'MAE_train': mae_train,
    'MAE': mae_val,
    'RMSE': rmse_val,
    'R2': r2_val,
    'MAPE': mape_val
}

print(f"\n✓ BiLSTM RESULTS:")
print(f"  Train MAE: {mae_train:.2f} cases")
print(f"  Val MAE:   {mae_val:.2f} cases")
print(f"  Val RMSE:  {rmse_val:.2f} cases")
print(f"  Val R²:    {r2_val:.4f}")
print(f"  Val MAPE:  {mape_val:.2f}%")

# =========================
# TRAIN MODELS SEPARATELY
# =========================

print("\n" + "="*70)
print("TRAINING DEEP LEARNING MODELS - ONE AT A TIME")
print("="*70)

input_shape = (X_train.shape[1], X_train.shape[2])
print(f"Input shape: {input_shape}\n")

# Callbacks
early_stop = EarlyStopping(monitor='val_loss', patience=15,
                          restore_best_weights=True, verbose=1)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=8,
                             min_lr=1e-7, verbose=1)

# Training config
EPOCHS = 80
BATCH_SIZE = 32
OPTIMIZER = keras.optimizers.Adam(learning_rate=0.002)

results = {}
# =========================
# MODEL 1: LSTM-ATTENTION
# =========================
print("\n" + "="*70)
print("TRAINING MODEL 1/4: LSTM-ATTENTION")
print("="*70)

model_lstm_attn = build_lstm_attention(input_shape, dropout=0.4)
model_lstm_attn.compile(optimizer=OPTIMIZER, loss='mse', metrics=['mae'])

history_lstm_attn = model_lstm_attn.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

# Predictions
y_pred_train = model_lstm_attn.predict(X_train, verbose=0).flatten()
y_pred_val = model_lstm_attn.predict(X_val, verbose=0).flatten()

# Inverse transform
y_pred_train_orig = scaler_y.inverse_transform(y_pred_train.reshape(-1, 1)).flatten()
y_pred_val_orig = scaler_y.inverse_transform(y_pred_val.reshape(-1, 1)).flatten()
y_train_orig = scaler_y.inverse_transform(y_train.reshape(-1, 1)).flatten()
y_val_orig = scaler_y.inverse_transform(y_val.reshape(-1, 1)).flatten()

# Metrics
mae_train = mean_absolute_error(y_train_orig, y_pred_train_orig)
mae_val = mean_absolute_error(y_val_orig, y_pred_val_orig)
rmse_val = np.sqrt(mean_squared_error(y_val_orig, y_pred_val_orig))
r2_val = r2_score(y_val_orig, y_pred_val_orig)
mape_val = np.mean(np.abs((y_val_orig - y_pred_val_orig) / (y_val_orig + 1))) * 100

results['LSTM-Attention'] = {
    'model': model_lstm_attn,
    'history': history_lstm_attn,
    'y_pred_val': y_pred_val_orig,
    'MAE_train': mae_train,
    'MAE': mae_val,
    'RMSE': rmse_val,
    'R2': r2_val,
    'MAPE': mape_val
}

print(f"\n✓ LSTM-ATTENTION RESULTS:")
print(f"  Train MAE: {mae_train:.2f} cases")
print(f"  Val MAE:   {mae_val:.2f} cases")
print(f"  Val RMSE:  {rmse_val:.2f} cases")
print(f"  Val R²:    {r2_val:.4f}")
print(f"  Val MAPE:  {mape_val:.2f}%")

# =========================
# TRAIN MODELS SEPARATELY(best dl modellll)
# =========================

print("\n" + "="*70)
print("TRAINING DEEP LEARNING MODELS - ONE AT A TIME")
print("="*70)

input_shape = (X_train.shape[1], X_train.shape[2])
print(f"Input shape: {input_shape}\n")

# Callbacks
early_stop = EarlyStopping(monitor='val_loss', patience=15,
                          restore_best_weights=True, verbose=1)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=8,
                             min_lr=1e-7, verbose=1)

# Training config
EPOCHS = 80
BATCH_SIZE = 32
OPTIMIZER = keras.optimizers.Adam(learning_rate=0.002)

results = {}
# =========================
# MODEL 2: CNN-LSTM
# =========================
print("\n" + "="*70)
print("TRAINING MODEL 2/4: CNN-LSTM")
print("="*70)

model_cnn_lstm = build_cnn_lstm(input_shape, dropout=0.4)
model_cnn_lstm.compile(optimizer=OPTIMIZER, loss='mse', metrics=['mae'])

history_cnn_lstm = model_cnn_lstm.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

# Predictions
y_pred_train = model_cnn_lstm.predict(X_train, verbose=0).flatten()
y_pred_val = model_cnn_lstm.predict(X_val, verbose=0).flatten()

# Inverse transform
y_pred_train_orig = scaler_y.inverse_transform(y_pred_train.reshape(-1, 1)).flatten()
y_pred_val_orig = scaler_y.inverse_transform(y_pred_val.reshape(-1, 1)).flatten()
y_train_orig = scaler_y.inverse_transform(y_train.reshape(-1, 1)).flatten()
y_val_orig = scaler_y.inverse_transform(y_val.reshape(-1, 1)).flatten()

# Metrics
mae_train = mean_absolute_error(y_train_orig, y_pred_train_orig)
mae_val = mean_absolute_error(y_val_orig, y_pred_val_orig)
rmse_val = np.sqrt(mean_squared_error(y_val_orig, y_pred_val_orig))
r2_val = r2_score(y_val_orig, y_pred_val_orig)
mape_val = np.mean(np.abs((y_val_orig - y_pred_val_orig) / (y_val_orig + 1))) * 100

results['CNN-LSTM'] = {
    'model': model_cnn_lstm,
    'history': history_cnn_lstm,
    'y_pred_val': y_pred_val_orig,
    'MAE_train': mae_train,
    'MAE': mae_val,
    'RMSE': rmse_val,
    'R2': r2_val,
    'MAPE': mape_val
}

print(f"\n✓ CNN-LSTM RESULTS:")
print(f"  Train MAE: {mae_train:.2f} cases")
print(f"  Val MAE:   {mae_val:.2f} cases")
print(f"  Val RMSE:  {rmse_val:.2f} cases")
print(f"  Val R²:    {r2_val:.4f}")
print(f"  Val MAPE:  {mape_val:.2f}%")



# =========================
# TRAIN MODELS SEPARATELY(overfittingggg)
# =========================

print("\n" + "="*70)
print("TRAINING DEEP LEARNING MODELS - ONE AT A TIME")
print("="*70)

input_shape = (X_train.shape[1], X_train.shape[2])
print(f"Input shape: {input_shape}\n")

# Callbacks
early_stop = EarlyStopping(monitor='val_loss', patience=15,
                          restore_best_weights=True, verbose=1)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=8,
                             min_lr=1e-7, verbose=1)

# Training config
EPOCHS = 80
BATCH_SIZE = 32
OPTIMIZER = keras.optimizers.Adam(learning_rate=0.002)

results = {}
# =========================
# MODEL 4: TRANSFORMER
# =========================
print("\n" + "="*70)
print("TRAINING MODEL 4/4: TRANSFORMER")
print("="*70)

model_transformer = build_transformer(input_shape, dropout=0.4)
model_transformer.compile(optimizer=OPTIMIZER, loss='mse', metrics=['mae'])

history_transformer = model_transformer.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

# Predictions
y_pred_train = model_transformer.predict(X_train, verbose=0).flatten()
y_pred_val = model_transformer.predict(X_val, verbose=0).flatten()

# Inverse transform
y_pred_train_orig = scaler_y.inverse_transform(y_pred_train.reshape(-1, 1)).flatten()
y_pred_val_orig = scaler_y.inverse_transform(y_pred_val.reshape(-1, 1)).flatten()
y_train_orig = scaler_y.inverse_transform(y_train.reshape(-1, 1)).flatten()
y_val_orig = scaler_y.inverse_transform(y_val.reshape(-1, 1)).flatten()

# Metrics
mae_train = mean_absolute_error(y_train_orig, y_pred_train_orig)
mae_val = mean_absolute_error(y_val_orig, y_pred_val_orig)
rmse_val = np.sqrt(mean_squared_error(y_val_orig, y_pred_val_orig))
r2_val = r2_score(y_val_orig, y_pred_val_orig)
mape_val = np.mean(np.abs((y_val_orig - y_pred_val_orig) / (y_val_orig + 1))) * 100

results['Transformer'] = {
    'model': model_transformer,
    'history': history_transformer,
    'y_pred_val': y_pred_val_orig,
    'MAE_train': mae_train,
    'MAE': mae_val,
    'RMSE': rmse_val,
    'R2': r2_val,
    'MAPE': mape_val
}

print(f"\n✓ TRANSFORMER RESULTS:")
print(f"  Train MAE: {mae_train:.2f} cases")
print(f"  Val MAE:   {mae_val:.2f} cases")
print(f"  Val RMSE:  {rmse_val:.2f} cases")
print(f"  Val R²:    {r2_val:.4f}")
print(f"  Val MAPE:  {mape_val:.2f}%")

# =========================
# REBUILD RESULTS DICTIONARY
# =========================

print("="*70)
print("REBUILDING RESULTS FROM ALL TRAINED MODELS")
print("="*70)

results = {}

# Check which models exist
if 'model_lstm_attn' in locals():
    y_pred_val = model_lstm_attn.predict(X_val, verbose=0).flatten()
    y_pred_val_orig = scaler_y.inverse_transform(y_pred_val.reshape(-1, 1)).flatten()
    y_val_orig = scaler_y.inverse_transform(y_val.reshape(-1, 1)).flatten()

    mae_val = mean_absolute_error(y_val_orig, y_pred_val_orig)
    rmse_val = np.sqrt(mean_squared_error(y_val_orig, y_pred_val_orig))
    r2_val = r2_score(y_val_orig, y_pred_val_orig)
    mape_val = np.mean(np.abs((y_val_orig - y_pred_val_orig) / (y_val_orig + 1))) * 100

    results['LSTM-Attention'] = {
        'y_pred_val': y_pred_val_orig,
        'MAE': mae_val,
        'RMSE': rmse_val,
        'R2': r2_val,
        'MAPE': mape_val
    }
    print("✓ LSTM-Attention loaded")

if 'model_cnn_lstm' in locals():
    y_pred_val = model_cnn_lstm.predict(X_val, verbose=0).flatten()
    y_pred_val_orig = scaler_y.inverse_transform(y_pred_val.reshape(-1, 1)).flatten()
    y_val_orig = scaler_y.inverse_transform(y_val.reshape(-1, 1)).flatten()

    mae_val = mean_absolute_error(y_val_orig, y_pred_val_orig)
    rmse_val = np.sqrt(mean_squared_error(y_val_orig, y_pred_val_orig))
    r2_val = r2_score(y_val_orig, y_pred_val_orig)
    mape_val = np.mean(np.abs((y_val_orig - y_pred_val_orig) / (y_val_orig + 1))) * 100

    results['CNN-LSTM'] = {
        'y_pred_val': y_pred_val_orig,
        'MAE': mae_val,
        'RMSE': rmse_val,
        'R2': r2_val,
        'MAPE': mape_val
    }
    print("✓ CNN-LSTM loaded")

if 'model_bilstm' in locals():
    y_pred_val = model_bilstm.predict(X_val, verbose=0).flatten()
    y_pred_val_orig = scaler_y.inverse_transform(y_pred_val.reshape(-1, 1)).flatten()
    y_val_orig = scaler_y.inverse_transform(y_val.reshape(-1, 1)).flatten()

    mae_val = mean_absolute_error(y_val_orig, y_pred_val_orig)
    rmse_val = np.sqrt(mean_squared_error(y_val_orig, y_pred_val_orig))
    r2_val = r2_score(y_val_orig, y_pred_val_orig)
    mape_val = np.mean(np.abs((y_val_orig - y_pred_val_orig) / (y_val_orig + 1))) * 100

    results['BiLSTM'] = {
        'y_pred_val': y_pred_val_orig,
        'MAE': mae_val,
        'RMSE': rmse_val,
        'R2': r2_val,
        'MAPE': mape_val
    }
    print("✓ BiLSTM loaded")

if 'model_transformer' in locals():
    y_pred_val = model_transformer.predict(X_val, verbose=0).flatten()
    y_pred_val_orig = scaler_y.inverse_transform(y_pred_val.reshape(-1, 1)).flatten()
    y_val_orig = scaler_y.inverse_transform(y_val.reshape(-1, 1)).flatten()

    mae_val = mean_absolute_error(y_val_orig, y_pred_val_orig)
    rmse_val = np.sqrt(mean_squared_error(y_val_orig, y_pred_val_orig))
    r2_val = r2_score(y_val_orig, y_pred_val_orig)
    mape_val = np.mean(np.abs((y_val_orig - y_pred_val_orig) / (y_val_orig + 1))) * 100

    results['Transformer'] = {
        'y_pred_val': y_pred_val_orig,
        'MAE': mae_val,
        'RMSE': rmse_val,
        'R2': r2_val,
        'MAPE': mape_val
    }
    print("✓ Transformer loaded")

print(f"\nTotal models loaded: {len(results)}")
print("="*70)

# Display summary
print("\nModel Summary:")
for name, res in sorted(results.items(), key=lambda x: x[1]['MAE']):
    print(f"  {name}: MAE={res['MAE']:.2f}, R²={res['R2']:.4f}")

# =========================
# 10. ENSEMBLE MODEL
# =========================

print("\n" + "="*70)
print("CREATING ENSEMBLE MODEL")
print("="*70)

# Weighted average ensemble (weight by validation performance)
weights = {}
total_inv_mae = 0
for name, res in results.items():
    inv_mae = 1 / res['MAE']
    weights[name] = inv_mae
    total_inv_mae += inv_mae

# Normalize weights
for name in weights:
    weights[name] /= total_inv_mae

print("\nEnsemble weights (based on validation MAE):")
for name, weight in weights.items():
    print(f"  {name}: {weight:.3f}")

# Ensemble predictions
y_pred_ensemble = np.zeros(len(y_val))
for name, res in results.items():
    y_pred_ensemble += weights[name] * res['y_pred_val']

# Ensemble metrics
y_val_orig = scaler_y.inverse_transform(y_val.reshape(-1, 1)).flatten()
mae_ensemble = mean_absolute_error(y_val_orig, y_pred_ensemble)
rmse_ensemble = np.sqrt(mean_squared_error(y_val_orig, y_pred_ensemble))
r2_ensemble = r2_score(y_val_orig, y_pred_ensemble)
mape_ensemble = np.mean(np.abs((y_val_orig - y_pred_ensemble) / (y_val_orig + 1))) * 100

print(f"\nEnsemble Results:")
print(f"  MAE:  {mae_ensemble:.2f}")
print(f"  RMSE: {rmse_ensemble:.2f}")
print(f"  R²:   {r2_ensemble:.4f}")
print(f"  MAPE: {mape_ensemble:.2f}%")

#=========================
# 11. RESULTS COMPARISON
# =========================

print("\n" + "="*70)
print("DEEP LEARNING MODEL COMPARISON")
print("="*70)

results_df = pd.DataFrame({
    'Model': list(results.keys()) + ['Ensemble'],
    'MAE': [results[k]['MAE'] for k in results.keys()] + [mae_ensemble],
    'RMSE': [results[k]['RMSE'] for k in results.keys()] + [rmse_ensemble],
    'R²': [results[k]['R2'] for k in results.keys()] + [r2_ensemble],
    'MAPE': [results[k]['MAPE'] for k in results.keys()] + [mape_ensemble]
})

results_df = results_df.sort_values('MAE')
print(results_df.to_string(index=False))

# =========================
# PLOT 1: ULTIMATE MODEL COMPARISON (CLEANER VERSION)
# =========================

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

sns.set_style("whitegrid")
plt.rcParams['figure.dpi'] = 100
plt.rcParams['font.size'] = 10

print("="*70)
print("GENERATING PLOT 1: Ultimate Model Comparison (Clean)")
print("="*70)

fig, ax = plt.subplots(figsize=(14, 8))

# All models data (ordered from best to worst)
all_models = [
    'Gradient Boosting',
    'XGBoost',
    'Random Forest',
    'CNN-LSTM',
    'DL Ensemble',
    'BiLSTM',
    'Transformer',
    'LSTM-Attention',
    'SEIRS+RK4'
]

mae_list = [2.21, 2.22, 5.80, 9.79, 10.42, 11.84, 12.37, 14.95, 34.35]

# Category labels (to add to model names)
category_labels = [
    'Gradient Boosting (ML)',
    'XGBoost (ML)',
    'Random Forest (ML)',
    'CNN-LSTM (DL)',
    'DL Ensemble (DL)',
    'BiLSTM (DL)',
    'Transformer (DL)',
    'LSTM-Attention (DL)',
    'SEIRS+RK4 (Mechanistic)'
]

# Color mapping
colors = [
    '#2ecc71',  # GB - Green
    '#27ae60',  # XGB - Green
    '#16a085',  # RF - Green
    '#3498db',  # CNN-LSTM - Blue
    '#2980b9',  # Ensemble - Blue
    '#5dade2',  # BiLSTM - Blue
    '#85c1e9',  # Transformer - Blue
    '#aed6f1',  # LSTM-Attn - Blue
    '#e74c3c'   # SEIRS - Red
]

# Create bars
bars = ax.barh(category_labels, mae_list, color=colors, edgecolor='black', linewidth=2, alpha=0.85)

# Add value labels
for i, (bar, val) in enumerate(zip(bars, mae_list)):
    ax.text(val + 0.8, i, f'{val:.2f}', va='center', fontweight='bold', fontsize=11)

# Add threshold line
ax.axvline(x=10, color='orange', linestyle='--', linewidth=2.5, alpha=0.8,
           label='Acceptable Threshold: MAE < 10', zorder=0)

# Labels and title
ax.set_xlabel('Mean Absolute Error (MAE) - Lower is Better', fontsize=13, fontweight='bold')
ax.set_title('Ultimate Model Comparison: ML vs DL vs Mechanistic\n(All 9 Models Tested)',
             fontsize=16, fontweight='bold', pad=20)
ax.legend(fontsize=11, loc='lower right')
ax.grid(axis='x', alpha=0.3, zorder=0)

# Set x-axis limit
ax.set_xlim(0, 37)

# Add background shading for categories
ax.axhspan(-0.5, 2.5, alpha=0.1, color='green', zorder=0)  # ML section
ax.axhspan(2.5, 7.5, alpha=0.1, color='blue', zorder=0)    # DL section
ax.axhspan(7.5, 8.5, alpha=0.1, color='red', zorder=0)     # Mechanistic section

# Add text labels on right side
ax.text(1.02, 0.15, 'Machine\nLearning', transform=ax.transAxes,
        fontsize=12, fontweight='bold', color='#2ecc71', va='center',
        bbox=dict(boxstyle='round,pad=0.8', facecolor='white', edgecolor='#2ecc71', linewidth=2))

ax.text(1.02, 0.55, 'Deep\nLearning', transform=ax.transAxes,
        fontsize=12, fontweight='bold', color='#3498db', va='center',
        bbox=dict(boxstyle='round,pad=0.8', facecolor='white', edgecolor='#3498db', linewidth=2))

ax.text(1.02, 0.92, 'Mechanistic', transform=ax.transAxes,
        fontsize=12, fontweight='bold', color='#e74c3c', va='center',
        bbox=dict(boxstyle='round,pad=0.8', facecolor='white', edgecolor='#e74c3c', linewidth=2))

plt.tight_layout()
plt.savefig('plot1_ultimate_comparison_clean.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: plot1_ultimate_comparison_clean.png")

# =========================
# PLOT 2: TOP 5 MODELS - DETAILED METRICS
# =========================

print("\n[2/5] Creating Top 5 Models Detailed Metrics...")

# Top 5 models with all metrics
top5_data = {
    'Model': ['Gradient\nBoosting', 'XGBoost', 'Random\nForest', 'CNN-LSTM', 'DL\nEnsemble'],
    'MAE': [2.21, 2.22, 5.80, 9.79, 10.42],
    'RMSE': [4.24, 4.32, 9.73, 16.25, 16.32],
    'R²': [0.988, 0.988, 0.937, 0.826, 0.824],
    'MAPE': [6.35, 6.27, 20.66, 43.52, 43.55]
}

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# MAE
axes[0, 0].barh(top5_data['Model'], top5_data['MAE'],
                color=['#2ecc71', '#27ae60', '#16a085', '#3498db', '#2980b9'],
                edgecolor='black', linewidth=2)
axes[0, 0].set_xlabel('MAE (cases)', fontsize=12, fontweight='bold')
axes[0, 0].set_title('Mean Absolute Error\n(Lower = Better)', fontsize=13, fontweight='bold')
axes[0, 0].grid(axis='x', alpha=0.3)
for i, v in enumerate(top5_data['MAE']):
    axes[0, 0].text(v + 0.3, i, f'{v:.2f}', va='center', fontweight='bold', fontsize=11)

# R²
axes[0, 1].barh(top5_data['Model'], top5_data['R²'],
                color=['#2ecc71', '#27ae60', '#16a085', '#3498db', '#2980b9'],
                edgecolor='black', linewidth=2)
axes[0, 1].set_xlabel('R² Score', fontsize=12, fontweight='bold')
axes[0, 1].set_title('R² - Variance Explained\n(Higher = Better)', fontsize=13, fontweight='bold')
axes[0, 1].axvline(x=0.8, color='orange', linestyle='--', linewidth=2, alpha=0.7, label='Excellent: R²>0.8')
axes[0, 1].grid(axis='x', alpha=0.3)
axes[0, 1].legend(fontsize=10)
for i, v in enumerate(top5_data['R²']):
    axes[0, 1].text(v + 0.01, i, f'{v:.3f}', va='center', fontweight='bold', fontsize=11)

# RMSE
axes[1, 0].barh(top5_data['Model'], top5_data['RMSE'],
                color=['#2ecc71', '#27ae60', '#16a085', '#3498db', '#2980b9'],
                edgecolor='black', linewidth=2)
axes[1, 0].set_xlabel('RMSE (cases)', fontsize=12, fontweight='bold')
axes[1, 0].set_title('Root Mean Squared Error\n(Lower = Better)', fontsize=13, fontweight='bold')
axes[1, 0].grid(axis='x', alpha=0.3)
for i, v in enumerate(top5_data['RMSE']):
    axes[1, 0].text(v + 0.5, i, f'{v:.2f}', va='center', fontweight='bold', fontsize=11)

# MAPE
axes[1, 1].barh(top5_data['Model'], top5_data['MAPE'],
                color=['#2ecc71', '#27ae60', '#16a085', '#3498db', '#2980b9'],
                edgecolor='black', linewidth=2)
axes[1, 1].set_xlabel('MAPE (%)', fontsize=12, fontweight='bold')
axes[1, 1].set_title('Mean Absolute % Error\n(Lower = Better)', fontsize=13, fontweight='bold')
axes[1, 1].grid(axis='x', alpha=0.3)
for i, v in enumerate(top5_data['MAPE']):
    axes[1, 1].text(v + 1, i, f'{v:.1f}%', va='center', fontweight='bold', fontsize=11)

plt.suptitle('Top 5 Models: Comprehensive Performance Metrics',
             fontsize=16, fontweight='bold', y=0.995)
plt.tight_layout()
plt.savefig('plot2_top5_metrics.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: plot2_top5_metrics.png")

# =========================
# PLOT 3: DL MODELS PREDICTIONS VS ACTUAL (FIXED)
# =========================

print("\n[3/5] Creating DL Predictions Comparison...")

# Get validation data
y_val_orig = scaler_y.inverse_transform(y_val.reshape(-1, 1)).flatten()
week_numbers = np.arange(1, len(y_val_orig) + 1)

fig, ax = plt.subplots(figsize=(18, 8))

# Plot actual
ax.plot(week_numbers, y_val_orig, 'o-', linewidth=3, markersize=8,
        label='Actual Cases', color='black', zorder=5)

# Plot DL model predictions (with error handling)
dl_models_to_plot = []

# Add models if they exist in results
if 'CNN-LSTM' in results:
    dl_models_to_plot.append(('CNN-LSTM', '#2ecc71', results['CNN-LSTM']['y_pred_val'], results['CNN-LSTM']['MAE']))

if 'BiLSTM' in results:
    dl_models_to_plot.append(('BiLSTM', '#3498db', results['BiLSTM']['y_pred_val'], results['BiLSTM']['MAE']))

if 'Transformer' in results:
    dl_models_to_plot.append(('Transformer', '#e74c3c', results['Transformer']['y_pred_val'], results['Transformer']['MAE']))

if 'LSTM-Attention' in results:
    dl_models_to_plot.append(('LSTM-Attention', '#f39c12', results['LSTM-Attention']['y_pred_val'], results['LSTM-Attention']['MAE']))

# Check for ensemble (might be named 'Ensemble' or 'DL Ensemble')
if 'Ensemble' in results:
    dl_models_to_plot.insert(2, ('DL Ensemble', '#9b59b6', results['Ensemble']['y_pred_val'], results['Ensemble']['MAE']))
elif 'DL Ensemble' in results:
    dl_models_to_plot.insert(2, ('DL Ensemble', '#9b59b6', results['DL Ensemble']['y_pred_val'], results['DL Ensemble']['MAE']))

# Plot each model
for name, color, preds, mae in dl_models_to_plot:
    ax.plot(week_numbers, preds, 's-', linewidth=2, markersize=4,
            label=f'{name} (MAE={mae:.2f})', color=color, alpha=0.7)

ax.set_xlabel('Week Number', fontsize=13, fontweight='bold')
ax.set_ylabel('Dengue Cases', fontsize=13, fontweight='bold')
ax.set_title('Deep Learning Models: Week-by-Week Predictions vs Actual\n(52-Week Validation Period)',
             fontsize=16, fontweight='bold', pad=20)
ax.legend(fontsize=11, loc='upper right')
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('plot3_dl_predictions.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: plot3_dl_predictions.png")

# =========================
# PLOT 4: ML vs DL vs MECHANISTIC CATEGORY COMPARISON
# =========================

print("\n[4/5] Creating Category Performance Comparison...")

fig, axes = plt.subplots(1, 3, figsize=(16, 6))

# Average performance by category
categories = ['Machine\nLearning', 'Deep\nLearning', 'Mechanistic']
avg_mae = [
    np.mean([2.21, 2.22, 5.80]),  # ML average
    np.mean([9.79, 10.42, 11.84, 12.37, 14.95]),  # DL average
    34.35  # SEIRS
]
best_mae = [2.21, 9.79, 34.35]  # Best in each category

# MAE Comparison
x = np.arange(len(categories))
width = 0.35

bars1 = axes[0].bar(x - width/2, avg_mae, width, label='Average MAE',
                    color=['#2ecc71', '#3498db', '#e74c3c'], alpha=0.7,
                    edgecolor='black', linewidth=2)
bars2 = axes[0].bar(x + width/2, best_mae, width, label='Best MAE',
                    color=['#27ae60', '#2980b9', '#c0392b'], alpha=0.9,
                    edgecolor='black', linewidth=2)

axes[0].set_ylabel('MAE (cases)', fontsize=12, fontweight='bold')
axes[0].set_title('MAE by Model Category', fontsize=13, fontweight='bold')
axes[0].set_xticks(x)
axes[0].set_xticklabels(categories)
axes[0].legend(fontsize=10)
axes[0].grid(axis='y', alpha=0.3)

for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        axes[0].text(bar.get_x() + bar.get_width()/2., height + 0.5,
                    f'{height:.1f}', ha='center', va='bottom', fontweight='bold', fontsize=10)

# Model Count
model_counts = [3, 5, 1]
bars3 = axes[1].bar(categories, model_counts,
                    color=['#2ecc71', '#3498db', '#e74c3c'], alpha=0.7,
                    edgecolor='black', linewidth=2)
axes[1].set_ylabel('Number of Models', fontsize=12, fontweight='bold')
axes[1].set_title('Models Tested per Category', fontsize=13, fontweight='bold')
axes[1].grid(axis='y', alpha=0.3)

for bar, count in zip(bars3, model_counts):
    height = bar.get_height()
    axes[1].text(bar.get_x() + bar.get_width()/2., height,
                f'{count}', ha='center', va='bottom', fontweight='bold', fontsize=12)

# Improvement over SEIRS
improvement = [(34.35 - mae) / 34.35 * 100 for mae in best_mae]
bars4 = axes[2].bar(categories, improvement,
                    color=['#2ecc71', '#3498db', '#e74c3c'], alpha=0.7,
                    edgecolor='black', linewidth=2)
axes[2].set_ylabel('Improvement over SEIRS (%)', fontsize=12, fontweight='bold')
axes[2].set_title('Performance Gain vs Baseline', fontsize=13, fontweight='bold')
axes[2].axhline(y=50, color='orange', linestyle='--', linewidth=2, alpha=0.7)
axes[2].grid(axis='y', alpha=0.3)

for bar, imp in zip(bars4, improvement):
    height = bar.get_height()
    axes[2].text(bar.get_x() + bar.get_width()/2., height + 1,
                f'{imp:.0f}%', ha='center', va='bottom', fontweight='bold', fontsize=11)

plt.suptitle('Model Category Comparison: ML vs DL vs Mechanistic',
             fontsize=16, fontweight='bold', y=1.00)
plt.tight_layout()
plt.savefig('plot4_category_comparison.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: plot4_category_comparison.png")

# =========================
# PLOT 5: BEST MODEL SCATTER PLOTS (ML vs DL)
# =========================

print("\n[5/5] Creating Best Model Scatter Comparison...")

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

# Need to get ML predictions (assuming you have comparison_df from earlier ML code)
# If not available, load from CSV
try:
    ml_comparison_df = pd.read_csv('ml_predictions.csv')
    ml_actual = ml_comparison_df['Actual_Cases'].values
    ml_predicted = ml_comparison_df['Predicted_Cases'].values
except:
    print("⚠️ Warning: ml_predictions.csv not found. Using dummy data for ML scatter.")
    ml_actual = y_val_orig
    ml_predicted = y_val_orig + np.random.normal(0, 2, len(y_val_orig))

max_val = max(y_val_orig.max(), ml_predicted.max(), results['CNN-LSTM']['y_pred_val'].max())

# ML Scatter (Gradient Boosting)
axes[0].scatter(ml_actual, ml_predicted, s=120, alpha=0.7,
                edgecolor='black', linewidth=1.5, c='#2ecc71', label='Predictions')
axes[0].plot([0, max_val], [0, max_val], 'r--', linewidth=3, label='Perfect Prediction')
axes[0].plot([0, max_val], [0, max_val+5], 'orange', linestyle=':', linewidth=2,
             alpha=0.7, label='±5 cases')
axes[0].plot([0, max_val], [0, max_val-5], 'orange', linestyle=':', linewidth=2, alpha=0.7)
axes[0].set_xlabel('Actual Cases', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Predicted Cases', fontsize=12, fontweight='bold')
axes[0].set_title('Best ML Model: Gradient Boosting\n(MAE=2.21, R²=0.988)',
                  fontsize=13, fontweight='bold')
axes[0].legend(fontsize=11, loc='upper left')
axes[0].grid(alpha=0.3)
axes[0].set_aspect('equal')

# DL Scatter (CNN-LSTM)
axes[1].scatter(y_val_orig, results['CNN-LSTM']['y_pred_val'], s=120, alpha=0.7,
                edgecolor='black', linewidth=1.5, c='#3498db', label='Predictions')
axes[1].plot([0, max_val], [0, max_val], 'r--', linewidth=3, label='Perfect Prediction')
axes[1].plot([0, max_val], [0, max_val+10], 'orange', linestyle=':', linewidth=2,
             alpha=0.7, label='±10 cases')
axes[1].plot([0, max_val], [0, max_val-10], 'orange', linestyle=':', linewidth=2, alpha=0.7)
axes[1].set_xlabel('Actual Cases', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Predicted Cases', fontsize=12, fontweight='bold')
axes[1].set_title('Best DL Model: CNN-LSTM\n(MAE=9.79, R²=0.826)',
                  fontsize=13, fontweight='bold')
axes[1].legend(fontsize=11, loc='upper left')
axes[1].grid(alpha=0.3)
axes[1].set_aspect('equal')

plt.suptitle('Scatter Plot Comparison: Best ML vs Best DL Model',
             fontsize=16, fontweight='bold', y=1.00)
plt.tight_layout()
plt.savefig('plot5_scatter_comparison.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: plot5_scatter_comparison.png")