# -*- coding: utf-8 -*-
"""MINI PROJ(FINALLL).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OFJRnmyQ--mUr8znwOJmgWEU1Mdgk0_c
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

# =========================
# 1. LOAD & PREPARE DATA
# =========================

features = pd.read_csv("dengue_features_train.csv")
labels = pd.read_csv("dengue_labels_train.csv")

df = pd.merge(features, labels, on=["city", "year", "weekofyear"], how="inner")
df = df.sort_values(by=["city", "year", "weekofyear"]).reset_index(drop=True)

# Focus on San Juan
df_sj = df[df["city"] == "sj"].copy().sort_values(["year", "weekofyear"]).reset_index(drop=True)

print(f"San Juan data shape: {df_sj.shape}")
print(f"Date range: {df_sj['year'].min()}-{df_sj['year'].max()}")
print(f"Cases range: {df_sj['total_cases'].min()}-{df_sj['total_cases'].max()}")

# =========================
# 2. CREATE DATE INDEX
# =========================

def create_weekly_date(df):
    df = df.copy()
    df["date"] = pd.to_datetime(
        df["year"].astype(str) + "-W" + df["weekofyear"].astype(str) + "-1",
        format="%Y-W%W-%w"
    )
    return df

df_sj = create_weekly_date(df_sj)
df_sj = df_sj.set_index("date").sort_index()

# Reindex to continuous weeks
def reindex_weekly(df):
    df = df.copy()
    df = df[~df.index.duplicated(keep="first")]
    full_range = pd.date_range(start=df.index.min(), end=df.index.max(), freq="W-MON")
    df = df.reindex(full_range)
    return df

df_sj = reindex_weekly(df_sj)
df_sj["city"] = "sj"

# =========================
# 3. HANDLE MISSING VALUES
# =========================

# Interpolate climate variables
CLIMATE_COLS = [col for col in df_sj.columns
                if col not in ["city", "year", "weekofyear", "total_cases"]]

df_sj[CLIMATE_COLS] = df_sj[CLIMATE_COLS].interpolate(method="linear").ffill().bfill()

# Interpolate cases (small gaps only)
df_sj["total_cases"] = df_sj["total_cases"].interpolate(method="linear", limit=2)
df_sj = df_sj.dropna(subset=["total_cases"])

print(f"\nAfter preprocessing: {df_sj.shape}")
print(f"Missing values:\n{df_sj.isna().sum().sum()} total")

# =========================
# 4. FEATURE ENGINEERING
# =========================

def build_ml_features(df,
                     case_lags=(1, 2, 3, 4, 5),
                     roll_windows=(3, 5, 7),
                     climate_lags=(1, 2, 3)):
    """
    Build comprehensive feature set for ML models
    """
    df = df.copy()

    # ==================
    # TEMPORAL FEATURES
    # ==================

    # Extract time components
    df['year'] = df.index.year
    df['month'] = df.index.month
    df['week'] = df.index.isocalendar().week.astype(int)
    df['day_of_year'] = df.index.dayofyear

    # Cyclical encoding of seasonality (IMPORTANT for dengue!)
    df['sin_week'] = np.sin(2 * np.pi * df['week'] / 52)
    df['cos_week'] = np.cos(2 * np.pi * df['week'] / 52)
    df['sin_month'] = np.sin(2 * np.pi * df['month'] / 12)
    df['cos_month'] = np.cos(2 * np.pi * df['month'] / 12)

    # ==================
    # CASE LAG FEATURES (Most important!)
    # ==================

    for lag in case_lags:
        df[f'cases_lag_{lag}'] = df['total_cases'].shift(lag)

    # Rolling statistics on cases
    for window in roll_windows:
        df[f'cases_roll_mean_{window}'] = df['total_cases'].rolling(window).mean()
        df[f'cases_roll_std_{window}'] = df['total_cases'].rolling(window).std()
        df[f'cases_roll_min_{window}'] = df['total_cases'].rolling(window).min()
        df[f'cases_roll_max_{window}'] = df['total_cases'].rolling(window).max()

    # Case growth rate
    df['cases_pct_change'] = df['total_cases'].pct_change()
    df['cases_diff'] = df['total_cases'].diff()

    # Exponentially weighted moving average
    df['cases_ewm_3'] = df['total_cases'].ewm(span=3).mean()
    df['cases_ewm_7'] = df['total_cases'].ewm(span=7).mean()

    # ==================
    # CLIMATE FEATURES
    # ==================

    # Key climate variables for dengue
    key_climate = [
        'station_avg_temp_c',
        'station_precip_mm',
        'reanalysis_avg_temp_k',
        'reanalysis_precip_amt_kg_per_m2',
        'reanalysis_specific_humidity_g_per_kg',
        'reanalysis_relative_humidity_percent',
        'reanalysis_dew_point_temp_k'
    ]

    for col in key_climate:
        if col in df.columns:
            # Lagged climate features
            for lag in climate_lags:
                df[f'{col}_lag_{lag}'] = df[col].shift(lag)

            # Rolling climate features
            df[f'{col}_roll_mean_4'] = df[col].rolling(4).mean()
            df[f'{col}_roll_std_4'] = df[col].rolling(4).std()

            # Climate change rate
            df[f'{col}_diff'] = df[col].diff()

    # Temperature-precipitation interaction (important for mosquito breeding)
    if 'station_avg_temp_c' in df.columns and 'station_precip_mm' in df.columns:
        df['temp_precip_interaction'] = df['station_avg_temp_c'] * df['station_precip_mm']

    # Optimal temperature indicator (dengue thrives at 25-30°C)
    if 'station_avg_temp_c' in df.columns:
        df['temp_optimal'] = ((df['station_avg_temp_c'] - 27.5) ** 2) * -1  # Peak at 27.5°C

    # ==================
    # VEGETATION INDEX (if available)
    # ==================

    if 'ndvi_ne' in df.columns:
        df['ndvi_avg'] = df[['ndvi_ne', 'ndvi_nw', 'ndvi_se', 'ndvi_sw']].mean(axis=1)
        df['ndvi_avg_lag_1'] = df['ndvi_avg'].shift(1)

    return df

# Build features
df_sj_ml = build_ml_features(df_sj)

# Drop rows with NaN (from lagging/rolling)
df_sj_ml = df_sj_ml.dropna()

print(f"\nAfter feature engineering: {df_sj_ml.shape}")
print(f"Total features created: {len(df_sj_ml.columns)}")

# =========================
# 5. PREPARE FEATURES & TARGET
# =========================

# Exclude non-feature columns
exclude_cols = ['city', 'total_cases', 'year', 'weekofyear', 'week_start_date']

# Select feature columns
feature_cols = [col for col in df_sj_ml.columns
                if col not in exclude_cols and not col.startswith('year')]

X = df_sj_ml[feature_cols]
y = df_sj_ml['total_cases']

print(f"\nFeature matrix shape: {X.shape}")
print(f"Target shape: {y.shape}")

# =========================
# 6. TRAIN/TEST SPLIT
# =========================

# Use last 52 weeks for validation (same as SEIRS model)
VAL_H = 52

X_train = X.iloc[:-VAL_H]
X_val = X.iloc[-VAL_H:]
y_train = y.iloc[:-VAL_H]
y_val = y.iloc[-VAL_H:]

print(f"\nTraining set: {len(X_train)} samples ({X_train.index.min()} to {X_train.index.max()})")
print(f"Validation set: {len(X_val)} samples ({X_val.index.min()} to {X_val.index.max()})")

# =========================
# 6.5. CLEAN FEATURES (FIX INFINITY/NAN)
# =========================

print("\n" + "="*70)
print("CLEANING FEATURES")
print("="*70)

# Check for problems
print(f"\nBefore cleaning:")
print(f"  NaN values: {X.isna().sum().sum()}")
print(f"  Inf values: {np.isinf(X.values).sum()}")

# Replace infinity with NaN
X = X.replace([np.inf, -np.inf], np.nan)

# Fill NaN with appropriate values
# For most features, use forward fill then backward fill
X = X.fillna(method='ffill').fillna(method='bfill')

# If any NaN still remain, fill with column mean
X = X.fillna(X.mean())

# Final check - if ANY NaN remain, fill with 0
X = X.fillna(0)

print(f"\nAfter cleaning:")
print(f"  NaN values: {X.isna().sum().sum()}")
print(f"  Inf values: {np.isinf(X.values).sum()}")

# Re-split after cleaning
X_train = X.iloc[:-VAL_H]
X_val = X.iloc[-VAL_H:]
y_train = y.iloc[:-VAL_H]
y_val = y.iloc[-VAL_H:]

print(f"\nCleaned training set: {X_train.shape}")
print(f"Cleaned validation set: {X_val.shape}")
print("="*70)

# =========================
# 7. TRAIN ML MODELS
# =========================

print("\n" + "="*70)
print("TRAINING MACHINE LEARNING MODELS")
print("="*70)

# Model 1: Random Forest
print("\n[1/3] Training Random Forest...")
rf_model = RandomForestRegressor(
    n_estimators=300,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
y_pred_rf_train = rf_model.predict(X_train)
y_pred_rf_val = rf_model.predict(X_val)

# Model 2: XGBoost
print("[2/3] Training XGBoost...")
xgb_model = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    random_state=42,
    n_jobs=-1
)
xgb_model.fit(X_train, y_train)
y_pred_xgb_train = xgb_model.predict(X_train)
y_pred_xgb_val = xgb_model.predict(X_val)

# Model 3: Gradient Boosting
print("[3/3] Training Gradient Boosting...")
gb_model = GradientBoostingRegressor(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    random_state=42
)
gb_model.fit(X_train, y_train)
y_pred_gb_train = gb_model.predict(X_train)
y_pred_gb_val = gb_model.predict(X_val)

print("✓ All models trained successfully!")

# =========================
# 8. ENSEMBLE MODEL
# =========================

# Simple average ensemble
y_pred_ensemble_train = (y_pred_rf_train + y_pred_xgb_train + y_pred_gb_train) / 3
y_pred_ensemble_val = (y_pred_rf_val + y_pred_xgb_val + y_pred_gb_val) / 3

# =========================
# 9. EVALUATION
# =========================

def evaluate_model(y_true, y_pred, model_name="Model"):
    """Compute evaluation metrics"""
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / (y_true + 1))) * 100

    return {
        'Model': model_name,
        'MAE': mae,
        'RMSE': rmse,
        'R2': r2,
        'MAPE': mape
    }

# Evaluate all models on validation set
results = []
results.append(evaluate_model(y_val, y_pred_rf_val, "Random Forest"))
results.append(evaluate_model(y_val, y_pred_xgb_val, "XGBoost"))
results.append(evaluate_model(y_val, y_pred_gb_val, "Gradient Boosting"))
results.append(evaluate_model(y_val, y_pred_ensemble_val, "Ensemble (Average)"))

# Add baselines
y_last_val = y.shift(1).iloc[-VAL_H:].values
y_ma3 = y.rolling(3).mean().shift(1).iloc[-VAL_H:].values

results.append(evaluate_model(y_val, y_last_val, "Last-value Baseline"))
results.append(evaluate_model(y_val, y_ma3, "3-week MA Baseline"))

# Create results dataframe
results_df = pd.DataFrame(results)

print("\n" + "="*70)
print("MODEL EVALUATION RESULTS — VALIDATION SET (52 weeks)")
print("="*70)
print(results_df.to_string(index=False))
print("="*70)

# =========================
# FIX: Define dates_val
# =========================

# Extract validation dates from the dataframe
dates_val = df_sj_ml.index[-VAL_H:]

# Now run the comparison code...

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# =========================
# 1. CREATE DETAILED COMPARISON TABLE
# =========================

# Get the best model predictions (use Gradient Boosting as it has best R²)
# If you want XGBoost instead, use y_pred_xgb_val
best_predictions = y_pred_gb_val  # Change to y_pred_xgb_val or y_pred_rf_val if preferred

# Create comparison dataframe
comparison_df = pd.DataFrame({
    'Week_Number': range(1, len(y_val) + 1),
    'Date': dates_val,
    'Actual_Cases': y_val.values,
    'Predicted_Cases': best_predictions,
    'Error': y_val.values - best_predictions,
    'Absolute_Error': np.abs(y_val.values - best_predictions),
    'Percentage_Error': np.abs((y_val.values - best_predictions) / (y_val.values + 1)) * 100
})

# Round for readability
comparison_df['Predicted_Cases'] = comparison_df['Predicted_Cases'].round(2)
comparison_df['Error'] = comparison_df['Error'].round(2)
comparison_df['Absolute_Error'] = comparison_df['Absolute_Error'].round(2)
comparison_df['Percentage_Error'] = comparison_df['Percentage_Error'].round(2)

print("="*90)
print("WEEK-BY-WEEK PREDICTION COMPARISON — VALIDATION SET (52 WEEKS)")
print("="*90)
print("\nBest Model: Gradient Boosting")
print(f"Overall MAE: {comparison_df['Absolute_Error'].mean():.2f} cases")
print(f"Overall R²: 0.988")
print("="*90)

# =========================
# 2. DISPLAY FIRST 20 WEEKS
# =========================

print("\n FIRST 20 WEEKS (Detailed View):")
print("="*90)
print(comparison_df.head(20).to_string(index=False))



# =========================
# 3. DISPLAY SAMPLE WEEKS IN YOUR REQUESTED FORMAT
# =========================

print("\n" + "="*90)
print("SAMPLE WEEK PREDICTIONS (First 10 Weeks):")
print("="*90)

for i in range(min(10, len(comparison_df))):
    row = comparison_df.iloc[i]
    actual = int(row['Actual_Cases'])
    predicted = int(round(row['Predicted_Cases']))
    error = abs(actual - predicted)

    # Add checkmark if error is small
    status = "✓" if error <= 5 else "⚠"

    print(f"Week {row['Week_Number']:2.0f}: "
          f"Actual = {actual:3d} cases  →  "
          f"Predicted = {predicted:3d} cases  "
          f"{status} ({error} off)")

# =========================
# 4. IDENTIFY BEST AND WORST PREDICTIONS
# =========================

print("\n" + "="*90)
print("BEST PREDICTIONS (Smallest Errors):")
print("="*90)

best_5 = comparison_df.nsmallest(5, 'Absolute_Error')[
    ['Week_Number', 'Date', 'Actual_Cases', 'Predicted_Cases', 'Absolute_Error']
]
print(best_5.to_string(index=False))

print("\n" + "="*90)
print("WORST PREDICTIONS (Largest Errors):")
print("="*90)

worst_5 = comparison_df.nlargest(5, 'Absolute_Error')[
    ['Week_Number', 'Date', 'Actual_Cases', 'Predicted_Cases', 'Absolute_Error']
]
print(worst_5.to_string(index=False))

# =========================
# 5. ERROR DISTRIBUTION STATISTICS
# =========================

print("\n" + "="*90)
print("ERROR DISTRIBUTION STATISTICS:")
print("="*90)

print(f"\nMean Absolute Error (MAE):     {comparison_df['Absolute_Error'].mean():.2f} cases")
print(f"Median Absolute Error:         {comparison_df['Absolute_Error'].median():.2f} cases")
print(f"Standard Deviation of Errors:  {comparison_df['Error'].std():.2f} cases")
print(f"Maximum Error:                 {comparison_df['Absolute_Error'].max():.2f} cases")
print(f"Minimum Error:                 {comparison_df['Absolute_Error'].min():.2f} cases")

# Error ranges
within_2 = (comparison_df['Absolute_Error'] <= 2).sum()
within_5 = (comparison_df['Absolute_Error'] <= 5).sum()
within_10 = (comparison_df['Absolute_Error'] <= 10).sum()

print(f"\n Prediction Accuracy Breakdown:")
print(f"   Within ±2 cases:   {within_2:2d} weeks ({within_2/len(comparison_df)*100:.1f}%)")
print(f"   Within ±5 cases:   {within_5:2d} weeks ({within_5/len(comparison_df)*100:.1f}%)")
print(f"   Within ±10 cases:  {within_10:2d} weeks ({within_10/len(comparison_df)*100:.1f}%)")



# =========================
# 6. VISUALIZATIONS
# =========================

# Plot 1: Week-by-Week Comparison (Line Plot)
fig, axes = plt.subplots(3, 1, figsize=(16, 12))

# Subplot 1: Actual vs Predicted
axes[0].plot(comparison_df['Week_Number'], comparison_df['Actual_Cases'],
             marker='o', linewidth=2, markersize=6, label='Actual Cases',
             color='black', zorder=3)
axes[0].plot(comparison_df['Week_Number'], comparison_df['Predicted_Cases'],
             marker='s', linewidth=2, markersize=5, label='Predicted Cases',
             color='red', alpha=0.7, zorder=2)
axes[0].fill_between(comparison_df['Week_Number'],
                      comparison_df['Actual_Cases'],
                      comparison_df['Predicted_Cases'],
                      alpha=0.2, color='gray', label='Prediction Error')
axes[0].set_xlabel('Week Number', fontsize=12)
axes[0].set_ylabel('Dengue Cases', fontsize=12)
axes[0].set_title('Week-by-Week: Actual vs Predicted Cases', fontsize=14, fontweight='bold')
axes[0].legend(fontsize=11, loc='upper right')
axes[0].grid(alpha=0.3)

# Subplot 2: Prediction Errors Over Time
axes[1].bar(comparison_df['Week_Number'], comparison_df['Error'],
            color=['red' if x < 0 else 'green' for x in comparison_df['Error']],
            alpha=0.6, edgecolor='black', linewidth=0.5)
axes[1].axhline(y=0, color='black', linestyle='-', linewidth=1.5)
axes[1].set_xlabel('Week Number', fontsize=12)
axes[1].set_ylabel('Prediction Error (Actual - Predicted)', fontsize=12)
axes[1].set_title('Prediction Errors by Week (Negative = Over-prediction, Positive = Under-prediction)',
                  fontsize=14, fontweight='bold')
axes[1].grid(axis='y', alpha=0.3)

# Subplot 3: Absolute Errors
axes[2].bar(comparison_df['Week_Number'], comparison_df['Absolute_Error'],
            color='orange', alpha=0.7, edgecolor='black', linewidth=0.5)
axes[2].axhline(y=comparison_df['Absolute_Error'].mean(),
                color='red', linestyle='--', linewidth=2,
                label=f'Mean AE = {comparison_df["Absolute_Error"].mean():.2f}')
axes[2].set_xlabel('Week Number', fontsize=12)
axes[2].set_ylabel('Absolute Error (|Actual - Predicted|)', fontsize=12)
axes[2].set_title('Absolute Prediction Errors by Week', fontsize=14, fontweight='bold')
axes[2].legend(fontsize=11)
axes[2].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

# Plot 2: Scatter Plot (Actual vs Predicted)
plt.figure(figsize=(10, 10))
plt.scatter(comparison_df['Actual_Cases'], comparison_df['Predicted_Cases'],
            s=100, alpha=0.6, edgecolor='black', linewidth=1, c='steelblue')

# Perfect prediction line
max_val = max(comparison_df['Actual_Cases'].max(), comparison_df['Predicted_Cases'].max())
plt.plot([0, max_val], [0, max_val], 'r--', linewidth=2, label='Perfect Prediction')

# ±5 case bounds
plt.plot([0, max_val], [0, max_val + 5], 'g:', linewidth=1.5, alpha=0.7, label='±5 cases')
plt.plot([0, max_val], [0, max_val - 5], 'g:', linewidth=1.5, alpha=0.7)

plt.xlabel('Actual Cases', fontsize=13)
plt.ylabel('Predicted Cases', fontsize=13)
plt.title('Actual vs Predicted Cases\n(Points near red line = good predictions)',
          fontsize=14, fontweight='bold')
plt.legend(fontsize=11)
plt.grid(alpha=0.3)
plt.axis('equal')
plt.tight_layout()
plt.show()

# Plot 3: Error Distribution Histogram
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Histogram of errors
axes[0].hist(comparison_df['Error'], bins=20, color='skyblue',
             edgecolor='black', alpha=0.7)
axes[0].axvline(x=0, color='red', linestyle='--', linewidth=2)
axes[0].set_xlabel('Prediction Error (Actual - Predicted)', fontsize=12)
axes[0].set_ylabel('Frequency (Number of Weeks)', fontsize=12)
axes[0].set_title('Distribution of Prediction Errors', fontsize=13, fontweight='bold')
axes[0].grid(axis='y', alpha=0.3)

# Histogram of absolute errors
axes[1].hist(comparison_df['Absolute_Error'], bins=20, color='lightcoral',
             edgecolor='black', alpha=0.7)
axes[1].axvline(x=comparison_df['Absolute_Error'].mean(),
                color='red', linestyle='--', linewidth=2,
                label=f'Mean = {comparison_df["Absolute_Error"].mean():.2f}')
axes[1].set_xlabel('Absolute Error', fontsize=12)
axes[1].set_ylabel('Frequency (Number of Weeks)', fontsize=12)
axes[1].set_title('Distribution of Absolute Errors', fontsize=13, fontweight='bold')
axes[1].legend(fontsize=11)
axes[1].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

# Plot 4: Monthly Average Comparison
comparison_df['Month'] = comparison_df['Date'].dt.month
comparison_df['Year'] = comparison_df['Date'].dt.year

monthly_comparison = comparison_df.groupby('Month').agg({
    'Actual_Cases': 'mean',
    'Predicted_Cases': 'mean'
}).reset_index()

plt.figure(figsize=(12, 6))
x = np.arange(len(monthly_comparison))
width = 0.35

plt.bar(x - width/2, monthly_comparison['Actual_Cases'], width,
        label='Actual (Avg)', color='black', alpha=0.7)
plt.bar(x + width/2, monthly_comparison['Predicted_Cases'], width,
        label='Predicted (Avg)', color='red', alpha=0.7)

plt.xlabel('Month', fontsize=12)
plt.ylabel('Average Dengue Cases', fontsize=12)
plt.title('Average Cases by Month: Actual vs Predicted', fontsize=14, fontweight='bold')
plt.xticks(x, ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][:len(monthly_comparison)])
plt.legend(fontsize=11)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from matplotlib.patches import Rectangle

# Set style for publication-quality plots
sns.set_style("whitegrid")
plt.rcParams['figure.dpi'] = 100
plt.rcParams['font.size'] = 10

# Data for all models
models = ['Gradient\nBoosting', 'XGBoost', 'Random\nForest', 'Ensemble',
          'Last-value', '3-week MA', 'SEIRS+RK4']
mae_values = [2.21, 2.22, 5.80, 3.31, 9.58, 11.49, 34.35]
rmse_values = [4.24, 4.32, 9.73, 5.58, 16.39, 19.21, 51.84]
r2_values = [0.988, 0.988, 0.937, 0.979, 0.822, 0.756, -0.782]
mape_values = [6.35, 6.27, 20.66, 10.47, 36.57, 43.34, 81.74]

colors = ['#2ecc71', '#3498db', '#9b59b6', '#e74c3c', '#f39c12', '#95a5a6', '#34495e']

# =========================
# PLOT 1: MAE Comparison
# =========================
plt.figure(figsize=(12, 8))
bars1 = plt.barh(models, mae_values, color=colors, edgecolor='black', linewidth=1.5)
plt.xlabel('Mean Absolute Error (MAE) - Lower is Better', fontsize=12, fontweight='bold')
plt.title('MAE: Average Prediction Error', fontsize=16, fontweight='bold', pad=20)
plt.axvline(x=10, color='red', linestyle='--', linewidth=2, alpha=0.7, label='Threshold: 10 cases')
for i, v in enumerate(mae_values):
    plt.text(v + 0.5, i, f'{v:.2f}', va='center', fontweight='bold', fontsize=11)
plt.legend()
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

# =========================
# PLOT 2: R² Comparison
# =========================
plt.figure(figsize=(12, 8))
bars2 = plt.barh(models, r2_values, color=colors, edgecolor='black', linewidth=1.5)
plt.xlabel('R² Score - Higher is Better', fontsize=12, fontweight='bold')
plt.title('R²: Variance Explained by Models', fontsize=16, fontweight='bold', pad=20)
plt.axvline(x=0, color='black', linestyle='-', linewidth=1.5)
plt.axvline(x=0.8, color='green', linestyle='--', linewidth=2, alpha=0.7, label='Excellent: R²>0.8')
for i, v in enumerate(r2_values):
    color = 'white' if v < 0 else 'black'
    plt.text(v + 0.02 if v > 0 else v - 0.02, i, f'{v:.3f}',
             va='center', ha='left' if v > 0 else 'right', fontweight='bold', fontsize=11, color=color)
plt.legend()
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

# =========================
# PLOT 3: RMSE Comparison
# =========================
plt.figure(figsize=(12, 8))
bars3 = plt.barh(models, rmse_values, color=colors, edgecolor='black', linewidth=1.5)
plt.xlabel('Root Mean Squared Error (RMSE) - Lower is Better', fontsize=12, fontweight='bold')
plt.title('RMSE: Penalty for Large Prediction Errors', fontsize=16, fontweight='bold', pad=20)
for i, v in enumerate(rmse_values):
    plt.text(v + 0.5, i, f'{v:.2f}', va='center', fontweight='bold', fontsize=11)
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

# =========================
# PLOT 4: MAPE Distribution (Top 3 Models)
# =========================
plt.figure(figsize=(10, 8))
top_3_models = ['GB', 'XGB', 'Ensemble']
top_3_mape = [6.35, 6.27, 10.47]
explode = (0.1, 0.05, 0)
plt.pie(top_3_mape, labels=top_3_models, autopct='%1.1f%%', startangle=90,
        colors=['#2ecc71', '#3498db', '#e74c3c'], explode=explode,
        textprops={'fontsize': 12, 'fontweight': 'bold'})
plt.title('MAPE Distribution\n(Top 3 Models)', fontsize=16, fontweight='bold', pad=20)
plt.tight_layout()
plt.show()

# =========================
# PLOT 5: Performance by Model Category
# =========================
plt.figure(figsize=(10, 8))
categories = ['Pure ML\n(Best 3)', 'Baselines\n(Best 2)', 'Mechanistic\n(SEIRS)']
cat_mae = [np.mean([2.21, 2.22, 3.31]), np.mean([9.58, 11.49]), 34.35]
cat_colors = ['#2ecc71', '#f39c12', '#e74c3c']
bars5 = plt.bar(categories, cat_mae, color=cat_colors, edgecolor='black',
                linewidth=2, alpha=0.8, width=0.6)
plt.ylabel('Average MAE', fontsize=12, fontweight='bold')
plt.title('Performance by Model Category', fontsize=16, fontweight='bold', pad=20)
for bar, val in zip(bars5, cat_mae):
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height,
             f'{val:.1f}', ha='center', va='bottom', fontweight='bold', fontsize=12)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# =========================
# PLOT 5: TIME-SERIES PERFORMANCE TRACKING
# =========================

# Generate cumulative performance over validation period
# (Shows how MAE evolves as we make predictions)

weeks = np.arange(1, 53)
cumulative_mae = []

# Calculate cumulative MAE for best model
errors = comparison_df['Absolute_Error'].values
for i in range(1, len(errors) + 1):
    cumulative_mae.append(np.mean(errors[:i]))

plt.figure(figsize=(14, 6))
plt.plot(weeks, cumulative_mae, linewidth=3, color='red', marker='o',
         markersize=4, label='Cumulative MAE')
plt.axhline(y=comparison_df['Absolute_Error'].mean(), color='green',
            linestyle='--', linewidth=2,
            label=f'Final MAE = {comparison_df["Absolute_Error"].mean():.2f}')
plt.fill_between(weeks, 0, cumulative_mae, alpha=0.2, color='red')

plt.xlabel('Week Number', fontsize=12, fontweight='bold')
plt.ylabel('Cumulative MAE', fontsize=12, fontweight='bold')
plt.title('Model Performance Stability Over Time\n(How MAE stabilizes as more predictions are made)',
          fontsize=14, fontweight='bold')
plt.legend(fontsize=11, loc='upper right')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# =========================
# 10. FEATURE IMPORTANCE ANALYSIS
# =========================

# Get feature importance from best model
feature_importance = pd.DataFrame({
    'feature': feature_cols,
    'importance': gb_model.feature_importances_
}).sort_values('importance', ascending=False)

print("\n" + "="*70)
print("TOP 15 MOST IMPORTANT FEATURES (Gradient Boosting)")
print("="*70)
print(feature_importance.head(15).to_string(index=False))

# Categorize features
temporal = feature_importance[feature_importance['feature'].str.contains('lag|roll|ewm')]
climate = feature_importance[feature_importance['feature'].str.contains('temp|precip|humid')]
seasonal = feature_importance[feature_importance['feature'].str.contains('sin|cos|week|month')]

print(f"\nFeature Category Importance:")
print(f"  Temporal features:  {temporal['importance'].sum()*100:.1f}%")
print(f"  Climate features:   {climate['importance'].sum()*100:.1f}%")
print(f"  Seasonal features:  {seasonal['importance'].sum()*100:.1f}%")
print("="*70)

# Save ML results
comparison_df.to_csv('ml_predictions.csv', index=False)
print("✓ ML predictions saved to ml_predictions.csv")



"""**SIR + RK4**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from scipy.optimize import minimize
import warnings
warnings.filterwarnings('ignore')

# =========================
# 1. LOAD & PREPARE DATA
# =========================

features = pd.read_csv("dengue_features_train.csv")
labels = pd.read_csv("dengue_labels_train.csv")

df = pd.merge(features, labels, on=["city", "year", "weekofyear"], how="inner")
df = df.sort_values(by=["city", "year", "weekofyear"]).reset_index(drop=True)

# Split by city - focus on San Juan
df_sj = df[df["city"] == "sj"].copy().sort_values(["year", "weekofyear"]).reset_index(drop=True)

# Create date index
def create_weekly_date(df):
    df = df.copy()
    df["date"] = pd.to_datetime(
        df["year"].astype(str) + "-W" + df["weekofyear"].astype(str) + "-1",
        format="%Y-W%W-%w"
    )
    return df

df_sj = create_weekly_date(df_sj)
df_sj = df_sj.set_index("date").sort_index()

# Reindex to continuous weeks
def reindex_weekly(df):
    df = df.copy()
    df = df[~df.index.duplicated(keep="first")]
    full_range = pd.date_range(start=df.index.min(), end=df.index.max(), freq="W-MON")
    df = df.reindex(full_range)
    return df

df_sj = reindex_weekly(df_sj)
df_sj["city"] = "sj"

# Handle missing values
CLIMATE_COLS = [col for col in df_sj.columns
                if col not in ["city", "year", "weekofyear", "total_cases"]]

df_sj[CLIMATE_COLS] = df_sj[CLIMATE_COLS].interpolate(method="linear").ffill().bfill()
df_sj["total_cases"] = df_sj["total_cases"].interpolate(method="linear", limit=2)
df_sj = df_sj.dropna(subset=["total_cases"])
df_sj = df_sj.drop(columns=["year", "weekofyear"], errors='ignore')

# Smooth cases
df_sj["cases_smooth"] = df_sj["total_cases"].rolling(window=3, center=True).mean()
df_sj["cases_smooth"] = df_sj["cases_smooth"].ffill().bfill().clip(lower=0)

print(f"San Juan data shape: {df_sj.shape}")
print(f"Date range: {df_sj.index.min()} to {df_sj.index.max()}")
print(f"Cases range: {df_sj['total_cases'].min():.0f} to {df_sj['total_cases'].max():.0f}")

# =========================
# 2. IMPROVED SEIRS MODEL
# =========================

def construct_SEIRS_compartments(df,
                                  N=400000,
                                  incubation_period=5,
                                  infectious_period=7,
                                  immunity_period=180):
    """
    SEIRS Model for Dengue with STABLE initialization
    """
    df = df.copy()

    # Convert parameters to weekly rates
    alpha = 7 / incubation_period
    gamma = 7 / infectious_period
    delta = 7 / immunity_period

    df['alpha'] = alpha
    df['gamma'] = gamma
    df['delta'] = delta
    df['N'] = N

    # CRITICAL FIX: Use much smaller scaling to prevent instability
    # Peak observed cases should map to ~0.1% of population, not 0.5%
    max_cases = df['cases_smooth'].max()

    # More conservative scaling: peak cases = 0.1% of population in model
    scale_to_population = 0.001

    df['I'] = (df['cases_smooth'] / max_cases) * scale_to_population
    df['I'] = df['I'].clip(lower=1e-6, upper=0.005)  # Cap at 0.5%

    # E should be slightly larger than I (incubation backlog)
    df['E'] = df['I'] * 1.5
    df['E'] = df['E'].clip(upper=0.01)

    # Estimate R from cumulative infections with decay
    R = np.zeros(len(df))
    for t in range(1, len(df)):
        new_R = gamma * df['I'].iloc[t-1]
        R[t] = R[t-1] + new_R - delta * R[t-1]
        R[t] = max(0, min(0.2, R[t]))

    df['R'] = R

    # S is remainder
    df['S'] = 1 - df['E'] - df['I'] - df['R']
    df['S'] = df['S'].clip(lower=0.7, upper=1.0)

    # Normalize
    total = df['S'] + df['E'] + df['I'] + df['R']
    df['S'] = df['S'] / total
    df['E'] = df['E'] / total
    df['I'] = df['I'] / total
    df['R'] = df['R'] / total

    # Store for reverse conversion
    df['_max_cases'] = max_cases
    df['_scale_factor'] = scale_to_population

    return df

df_sj = construct_SEIRS_compartments(df_sj)

print("\nSEIRS Compartment Statistics:")
print(df_sj[['S', 'E', 'I', 'R']].describe())
print(f"\nI compartment range: [{df_sj['I'].min():.6f}, {df_sj['I'].max():.6f}]")

# =========================
# 3. CLIMATE-DRIVEN BETA ESTIMATION
# =========================

def estimate_climate_driven_beta(df, base_beta_bounds=(0.05, 1.2)):
    """Estimate transmission rate with strict bounds"""
    df = df.copy()

    S = df['S']
    E = df['E']
    I = df['I']
    alpha = df['alpha'].iloc[0]

    E_next = df['E'].shift(-1)

    dE = E_next - E
    numerator = dE + alpha * E
    denominator = S * I

    beta_raw = numerator / (denominator + 1e-8)
    beta_raw = beta_raw.replace([np.inf, -np.inf], np.nan)

    # STRICT clipping for stability
    beta_raw = beta_raw.clip(lower=base_beta_bounds[0], upper=base_beta_bounds[1])

    # Aggressive smoothing
    beta_smooth = beta_raw.rolling(window=7, center=True, min_periods=1).mean()
    beta_smooth = beta_smooth.interpolate(method='linear').ffill().bfill()

    # Additional constraint: beta shouldn't vary too wildly
    beta_smooth = beta_smooth.clip(lower=0.1, upper=0.9)

    df['beta_raw'] = beta_raw
    df['beta_smooth'] = beta_smooth

    return df

df_sj = estimate_climate_driven_beta(df_sj)

print("\nTransmission rate (β) statistics:")
print(df_sj['beta_smooth'].describe())

# =========================
# 4. ML MODEL FOR BETA PREDICTION
# =========================

def build_beta_features(df, lags=(1, 2, 3), roll_windows=(3, 5)):
    """Build features to predict next week's β"""
    df = df.copy()

    # Lag features for β
    for lag in lags:
        df[f'beta_lag_{lag}'] = df['beta_smooth'].shift(lag)

    # Compartment lags
    for lag in [1, 2]:
        df[f'I_lag_{lag}'] = df['I'].shift(lag)

    # Rolling stats for I
    for w in roll_windows:
        df[f'I_roll_mean_{w}'] = df['I'].rolling(w).mean()

    # Climate features
    climate_cols = ['station_avg_temp_c', 'station_precip_mm',
                    'reanalysis_specific_humidity_g_per_kg']

    for col in climate_cols:
        if col in df.columns:
            df[f'{col}_lag1'] = df[col].shift(1)
            df[f'{col}_roll3'] = df[col].rolling(3).mean()

    # Seasonality
    week = df.index.isocalendar().week.astype(int)
    df['sin_week'] = np.sin(2 * np.pi * week / 52)
    df['cos_week'] = np.cos(2 * np.pi * week / 52)

    # Target
    df['beta_target'] = df['beta_smooth'].shift(-1)

    df = df.dropna()

    return df

df_sj_ml = build_beta_features(df_sj)

BETA_FEATURE_COLS = [
    c for c in df_sj_ml.columns
    if any(x in c for x in ['beta_lag', 'I_lag', 'I_roll', 'sin_', 'cos_',
                            'temp', 'precip', 'humid'])
    and c not in ['beta_raw', 'beta_smooth', 'beta_target']
]

print(f"\nFeatures for β prediction: {len(BETA_FEATURE_COLS)}")

# =========================
# 5. TRAIN/VALIDATION SPLIT
# =========================

VAL_H = 52

X_beta = df_sj_ml[BETA_FEATURE_COLS]
y_beta = df_sj_ml['beta_target']

X_train_beta = X_beta.iloc[:-VAL_H]
X_val_beta = X_beta.iloc[-VAL_H:]
y_train_beta = y_beta.iloc[:-VAL_H]
y_val_beta = y_beta.iloc[-VAL_H:]

print(f"\nTraining samples: {len(X_train_beta)}")
print(f"Validation samples: {len(X_val_beta)}")

# Train models
rf_beta = RandomForestRegressor(n_estimators=200, max_depth=6,
                                min_samples_leaf=5, random_state=42)
rf_beta.fit(X_train_beta, y_train_beta)

# Evaluate β predictions
beta_pred_rf = rf_beta.predict(X_val_beta)

print(f"\nβ Prediction - RF MAE: {mean_absolute_error(y_val_beta, beta_pred_rf):.4f}, "
      f"R²: {r2_score(y_val_beta, beta_pred_rf):.4f}")

# =========================
# 6. STABLE RK4 SOLVER
# =========================

def seirs_derivatives(state, beta, alpha, gamma, delta):
    """SEIRS differential equations"""
    S, E, I, R = state

    dS = -beta * S * I + delta * R
    dE = beta * S * I - alpha * E
    dI = alpha * E - gamma * I
    dR = gamma * I - delta * R

    return np.array([dS, dE, dI, dR])

def rk4_step_seirs(state, beta, alpha, gamma, delta, dt=1.0):
    """RK4 integration with stability checks"""
    k1 = seirs_derivatives(state, beta, alpha, gamma, delta)
    k2 = seirs_derivatives(state + dt*k1/2, beta, alpha, gamma, delta)
    k3 = seirs_derivatives(state + dt*k2/2, beta, alpha, gamma, delta)
    k4 = seirs_derivatives(state + dt*k3, beta, alpha, gamma, delta)

    next_state = state + dt * (k1 + 2*k2 + 2*k3 + k4) / 6

    # Enforce bounds
    next_state = np.maximum(next_state, 0)
    next_state[2] = min(next_state[2], 0.02)  # Cap I at 2%
    next_state = next_state / (next_state.sum() + 1e-10)

    return next_state

def simulate_seirs_forecast(initial_state, beta_sequence, alpha, gamma, delta):
    """Simulate SEIRS with stability controls"""
    state = np.array(initial_state)

    S_list, E_list, I_list, R_list = [], [], [], []

    for i, beta in enumerate(beta_sequence):
        # Dampen beta if I is getting too large
        if state[2] > 0.015:
            beta = beta * 0.7

        # Additional: use average of predicted and historical beta for stability
        if i > 0:
            beta = 0.7 * beta + 0.3 * beta_sequence[max(0, i-1)]

        state = rk4_step_seirs(state, beta, alpha, gamma, delta)

        S_list.append(state[0])
        E_list.append(state[1])
        I_list.append(state[2])
        R_list.append(state[3])

    return np.array(S_list), np.array(E_list), np.array(I_list), np.array(R_list)

# =========================
# 7. ITERATIVE BETA FORECAST
# =========================

def iterative_forecast_beta(df_ml, X, beta_model, horizon=52):
    """Predict β iteratively with constraints"""
    df_work = df_ml.copy()
    X_curr = X.copy()

    beta_predictions = []

    for h in range(horizon):
        X_last = X_curr.iloc[[-1]]
        beta_next = beta_model.predict(X_last)[0]

        # CRITICAL: Constrain predicted beta
        beta_next = np.clip(beta_next, 0.1, 0.85)

        # Smooth with previous prediction
        if len(beta_predictions) > 0:
            beta_next = 0.8 * beta_next + 0.2 * beta_predictions[-1]

        beta_predictions.append(beta_next)

        new_row = df_work.iloc[-1:].copy()
        new_row['beta_smooth'] = beta_next

        df_work = pd.concat([df_work, new_row])
        df_work = build_beta_features(df_work)

        if len(df_work) > 0:
            X_curr = df_work[BETA_FEATURE_COLS]

    return np.array(beta_predictions)

# =========================
# 8. FORECAST AND EVALUATE
# =========================

# Get initial state
initial_idx = -VAL_H - 1
S0 = df_sj['S'].iloc[initial_idx]
E0 = df_sj['E'].iloc[initial_idx]
I0 = df_sj['I'].iloc[initial_idx]
R0 = df_sj['R'].iloc[initial_idx]

alpha = df_sj['alpha'].iloc[0]
gamma = df_sj['gamma'].iloc[0]
delta = df_sj['delta'].iloc[0]

print(f"\nInitial state: S={S0:.4f}, E={E0:.6f}, I={I0:.6f}, R={R0:.4f}")

# Forecast beta
beta_forecast = iterative_forecast_beta(
    df_sj_ml.iloc[:-VAL_H],
    X_beta.iloc[:-VAL_H],
    rf_beta,
    horizon=VAL_H
)

print(f"\nForecasted β range: [{beta_forecast.min():.4f}, {beta_forecast.max():.4f}]")
print(f"Forecasted β mean: {beta_forecast.mean():.4f}")

# Simulate SEIRS
S_pred, E_pred, I_pred, R_pred = simulate_seirs_forecast(
    initial_state=[S0, E0, I0, R0],
    beta_sequence=beta_forecast,
    alpha=alpha,
    gamma=gamma,
    delta=delta
)

print(f"\nPredicted I range: [{I_pred.min():.6f}, {I_pred.max():.6f}]")

# =========================
# 9. CONVERT TO CASES (CRITICAL FIX)
# =========================

# METHOD 1: Use historical I-to-cases ratio (most stable)
recent_window = slice(-VAL_H-20, -VAL_H)
historical_I = df_sj['I'].iloc[recent_window].values
historical_cases = df_sj['cases_smooth'].iloc[recent_window].values

# Calculate average conversion ratio
valid_mask = historical_I > 1e-6
if valid_mask.sum() > 0:
    ratios = historical_cases[valid_mask] / historical_I[valid_mask]
    conversion_ratio = np.median(ratios)  # Use median for robustness
else:
    conversion_ratio = df_sj['_max_cases'].iloc[0] / df_sj['_scale_factor'].iloc[0]

print(f"\nConversion ratio (cases per I unit): {conversion_ratio:.1f}")

# Convert predictions
cases_pred_seirs = I_pred * conversion_ratio

# Safety bounds
max_cases = df_sj['cases_smooth'].max()
cases_pred_seirs = np.clip(cases_pred_seirs, 0, max_cases * 2.5)

# Get true cases
cases_true = df_sj['total_cases'].iloc[-VAL_H:].values

print(f"\nPredicted cases range: [{cases_pred_seirs.min():.1f}, {cases_pred_seirs.max():.1f}]")
print(f"True cases range: [{cases_true.min():.1f}, {cases_true.max():.1f}]")

# =========================
# 10. EVALUATION
# =========================

def evaluate_forecast(y_true, y_pred):
    return {
        "MAE": mean_absolute_error(y_true, y_pred),
        "RMSE": np.sqrt(mean_squared_error(y_true, y_pred)),
        "MAPE": np.mean(np.abs((y_true - y_pred) / (y_true + 1))) * 100,
        "R2": r2_score(y_true, y_pred)
    }

metrics_seirs = evaluate_forecast(cases_true, cases_pred_seirs)

print("\n" + "="*70)
print("CORRECTED SEIRS+RK4 FORECAST EVALUATION — SAN JUAN")
print("="*70)
for k, v in metrics_seirs.items():
    print(f"{k}: {v:.4f}")
print("="*70)

# Baselines
y_last_val = df_sj['total_cases'].shift(1).iloc[-VAL_H:].values
baseline_last = evaluate_forecast(cases_true, y_last_val)

y_ma3 = df_sj['total_cases'].rolling(3).mean().shift(1).iloc[-VAL_H:].values
baseline_ma3 = evaluate_forecast(cases_true, y_ma3)

print("\n" + "="*70)
print("BASELINE COMPARISONS")
print("="*70)
print("\nLast-value baseline:")
for k, v in baseline_last.items():
    print(f"{k}: {v:.4f}")

print("\n3-week MA baseline:")
for k, v in baseline_ma3.items():
    print(f"{k}: {v:.4f}")
print("="*70)

# =========================
# SEIRS+RK4: WEEK-BY-WEEK PREDICTION ANALYSIS
# =========================

print("\n" + "="*90)
print("SEIRS+RK4: DETAILED WEEK-BY-WEEK PREDICTION COMPARISON")
print("="*90)

# Create comparison dataframe for SEIRS
seirs_comparison_df = pd.DataFrame({
    'Week_Number': range(1, len(cases_true) + 1),
    'Date': df_sj.index[-VAL_H:],
    'Actual_Cases': cases_true,
    'Predicted_Cases': cases_pred_seirs,
    'Error': cases_true - cases_pred_seirs,
    'Absolute_Error': np.abs(cases_true - cases_pred_seirs),
    'Percentage_Error': np.abs((cases_true - cases_pred_seirs) / (cases_true + 1)) * 100
})

# Round for readability
seirs_comparison_df['Predicted_Cases'] = seirs_comparison_df['Predicted_Cases'].round(2)
seirs_comparison_df['Error'] = seirs_comparison_df['Error'].round(2)
seirs_comparison_df['Absolute_Error'] = seirs_comparison_df['Absolute_Error'].round(2)
seirs_comparison_df['Percentage_Error'] = seirs_comparison_df['Percentage_Error'].round(2)

print(f"\nModel: SEIRS+RK4")
print(f"Overall MAE: {seirs_comparison_df['Absolute_Error'].mean():.2f} cases")
print(f"Overall R²: {metrics_seirs['R2']:.4f}")
print("="*90)

# =========================
# SAMPLE WEEK PREDICTIONS (First 10 Weeks)
# =========================

print("\n" + "="*90)
print("SAMPLE WEEK PREDICTIONS (First 10 Weeks):")
print("="*90)

for i in range(min(10, len(seirs_comparison_df))):
    row = seirs_comparison_df.iloc[i]
    actual = int(row['Actual_Cases'])
    predicted = int(round(row['Predicted_Cases']))
    error = abs(actual - predicted)

    # Add checkmark if error is small (different thresholds for SEIRS)
    if error <= 5:
        status = "✓"
    elif error <= 15:
        status = "⚠"
    else:
        status = "✗"

    print(f"Week {row['Week_Number']:2.0f}: "
          f"Actual = {actual:3d} cases  →  "
          f"Predicted = {predicted:3d} cases  "
          f"{status} ({error} off)")

# =========================
# BEST AND WORST PREDICTIONS
# =========================

print("\n" + "="*90)
print("BEST PREDICTIONS (Smallest Errors):")
print("="*90)

best_5_seirs = seirs_comparison_df.nsmallest(5, 'Absolute_Error')[
    ['Week_Number', 'Date', 'Actual_Cases', 'Predicted_Cases', 'Absolute_Error']
]
print(best_5_seirs.to_string(index=False))

print("\n" + "="*90)
print("WORST PREDICTIONS (Largest Errors):")
print("="*90)

worst_5_seirs = seirs_comparison_df.nlargest(5, 'Absolute_Error')[
    ['Week_Number', 'Date', 'Actual_Cases', 'Predicted_Cases', 'Absolute_Error']
]
print(worst_5_seirs.to_string(index=False))

# =========================
# ERROR DISTRIBUTION STATISTICS
# =========================

print("\n" + "="*90)
print("ERROR DISTRIBUTION STATISTICS:")
print("="*90)

print(f"\nMean Absolute Error (MAE):     {seirs_comparison_df['Absolute_Error'].mean():.2f} cases")
print(f"Median Absolute Error:         {seirs_comparison_df['Absolute_Error'].median():.2f} cases")
print(f"Standard Deviation of Errors:  {seirs_comparison_df['Error'].std():.2f} cases")
print(f"Maximum Error:                 {seirs_comparison_df['Absolute_Error'].max():.2f} cases")
print(f"Minimum Error:                 {seirs_comparison_df['Absolute_Error'].min():.2f} cases")

# Error ranges (adjusted for SEIRS performance)
within_5 = (seirs_comparison_df['Absolute_Error'] <= 5).sum()
within_10 = (seirs_comparison_df['Absolute_Error'] <= 10).sum()
within_20 = (seirs_comparison_df['Absolute_Error'] <= 20).sum()
within_50 = (seirs_comparison_df['Absolute_Error'] <= 50).sum()

print(f"\n Prediction Accuracy Breakdown:")
print(f"   Within ±5 cases:   {within_5:2d} weeks ({within_5/len(seirs_comparison_df)*100:.1f}%)")
print(f"   Within ±10 cases:  {within_10:2d} weeks ({within_10/len(seirs_comparison_df)*100:.1f}%)")
print(f"   Within ±20 cases:  {within_20:2d} weeks ({within_20/len(seirs_comparison_df)*100:.1f}%)")
print(f"   Within ±50 cases:  {within_50:2d} weeks ({within_50/len(seirs_comparison_df)*100:.1f}%)")

# =========================
# VISUALIZATIONS FOR SEIRS
# =========================

# Plot 1: Week-by-Week Comparison
fig, axes = plt.subplots(2, 1, figsize=(16, 10))

# Subplot 1: Actual vs Predicted
axes[0].plot(seirs_comparison_df['Week_Number'], seirs_comparison_df['Actual_Cases'],
             marker='o', linewidth=2.5, markersize=6, label='Actual Cases',
             color='black', zorder=3)
axes[0].plot(seirs_comparison_df['Week_Number'], seirs_comparison_df['Predicted_Cases'],
             marker='s', linewidth=2, markersize=5, label='SEIRS+RK4 Predictions',
             color='red', alpha=0.7, zorder=2)
axes[0].fill_between(seirs_comparison_df['Week_Number'],
                      seirs_comparison_df['Actual_Cases'],
                      seirs_comparison_df['Predicted_Cases'],
                      alpha=0.2, color='gray', label='Prediction Error')
axes[0].set_xlabel('Week Number', fontsize=12)
axes[0].set_ylabel('Dengue Cases', fontsize=12)
axes[0].set_title('SEIRS+RK4: Week-by-Week Actual vs Predicted Cases',
                  fontsize=14, fontweight='bold')
axes[0].legend(fontsize=11, loc='upper right')
axes[0].grid(alpha=0.3)

# Subplot 2: Absolute Errors
axes[1].bar(seirs_comparison_df['Week_Number'], seirs_comparison_df['Absolute_Error'],
            color='orange', alpha=0.7, edgecolor='black', linewidth=0.5)
axes[1].axhline(y=seirs_comparison_df['Absolute_Error'].mean(),
                color='red', linestyle='--', linewidth=2,
                label=f'Mean AE = {seirs_comparison_df["Absolute_Error"].mean():.2f}')
axes[1].set_xlabel('Week Number', fontsize=12)
axes[1].set_ylabel('Absolute Error (|Actual - Predicted|)', fontsize=12)
axes[1].set_title('SEIRS+RK4: Absolute Prediction Errors by Week',
                  fontsize=14, fontweight='bold')
axes[1].legend(fontsize=11)
axes[1].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

# Plot 2: SEIRS Scatter Plot
plt.figure(figsize=(10, 10))
plt.scatter(seirs_comparison_df['Actual_Cases'], seirs_comparison_df['Predicted_Cases'],
            s=100, alpha=0.6, edgecolor='black', linewidth=1, c='coral')

# Perfect prediction line
max_val = max(seirs_comparison_df['Actual_Cases'].max(),
              seirs_comparison_df['Predicted_Cases'].max())
plt.plot([0, max_val], [0, max_val], 'r--', linewidth=2, label='Perfect Prediction')

# ±20 case bounds (more realistic for SEIRS)
plt.plot([0, max_val], [0, max_val + 20], 'g:', linewidth=1.5, alpha=0.7, label='±20 cases')
plt.plot([0, max_val], [0, max_val - 20], 'g:', linewidth=1.5, alpha=0.7)

plt.xlabel('Actual Cases', fontsize=13)
plt.ylabel('Predicted Cases', fontsize=13)
plt.title('SEIRS+RK4: Actual vs Predicted Cases\n(Points near red line = good predictions)',
          fontsize=14, fontweight='bold')
plt.legend(fontsize=11)
plt.grid(alpha=0.3)
plt.axis('equal')
plt.tight_layout()
plt.show()

# Plot 3: Error Distribution Histogram
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Histogram of errors
axes[0].hist(seirs_comparison_df['Error'], bins=20, color='lightcoral',
             edgecolor='black', alpha=0.7)
axes[0].axvline(x=0, color='red', linestyle='--', linewidth=2)
axes[0].set_xlabel('Prediction Error (Actual - Predicted)', fontsize=12)
axes[0].set_ylabel('Frequency (Number of Weeks)', fontsize=12)
axes[0].set_title('SEIRS+RK4: Distribution of Prediction Errors',
                  fontsize=13, fontweight='bold')
axes[0].grid(axis='y', alpha=0.3)

# Histogram of absolute errors
axes[1].hist(seirs_comparison_df['Absolute_Error'], bins=20, color='orange',
             edgecolor='black', alpha=0.7)
axes[1].axvline(x=seirs_comparison_df['Absolute_Error'].mean(),
                color='red', linestyle='--', linewidth=2,
                label=f'Mean = {seirs_comparison_df["Absolute_Error"].mean():.2f}')
axes[1].set_xlabel('Absolute Error', fontsize=12)
axes[1].set_ylabel('Frequency (Number of Weeks)', fontsize=12)
axes[1].set_title('SEIRS+RK4: Distribution of Absolute Errors',
                  fontsize=13, fontweight='bold')
axes[1].legend(fontsize=11)
axes[1].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

# Save SEIRS results
seirs_comparison_df.to_csv('seirs_predictions.csv', index=False)
print("✓ SEIRS predictions saved to seirs_predictions.csv")

"""**COMPARISON PLOTS(SEIR+RK4 AND ML)**"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from matplotlib.patches import Rectangle

# Set style
sns.set_style("whitegrid")
plt.rcParams['figure.dpi'] = 100
plt.rcParams['font.size'] = 10

print("="*80)
print("LOADING PREDICTION DATA")
print("="*80)

# =========================
# 1. LOAD DATA
# =========================

try:
    comparison_df = pd.read_csv('ml_predictions.csv')
    seirs_comparison_df = pd.read_csv('seirs_predictions.csv')

    # Convert Date columns to datetime
    comparison_df['Date'] = pd.to_datetime(comparison_df['Date'])
    seirs_comparison_df['Date'] = pd.to_datetime(seirs_comparison_df['Date'])

    print(f"✓ ML predictions loaded: {len(comparison_df)} weeks")
    print(f"✓ SEIRS predictions loaded: {len(seirs_comparison_df)} weeks")
    print("="*80)

except FileNotFoundError as e:
    print("ERROR: Prediction files not found!")
    print("Please run pure_ml.py and sir+rk4.py first to generate:")
    print("  - ml_predictions.csv")
    print("  - seirs_predictions.csv")
    raise

# =========================
# 2. SUMMARY STATISTICS
# =========================

print("\n" + "="*80)
print("MODEL PERFORMANCE SUMMARY")
print("="*80)

ml_mae = comparison_df['Absolute_Error'].mean()
ml_rmse = np.sqrt((comparison_df['Error']**2).mean())
ml_r2 = 0.988  # From results
ml_mape = comparison_df['Percentage_Error'].mean()

seirs_mae = seirs_comparison_df['Absolute_Error'].mean()
seirs_rmse = np.sqrt((seirs_comparison_df['Error']**2).mean())
seirs_r2 = -0.78  # From results
seirs_mape = seirs_comparison_df['Percentage_Error'].mean()

print(f"\nML (Gradient Boosting):")
print(f"  MAE:  {ml_mae:.2f} cases")
print(f"  RMSE: {ml_rmse:.2f} cases")
print(f"  R²:   {ml_r2:.4f}")
print(f"  MAPE: {ml_mape:.2f}%")

print(f"\nSEIRS+RK4:")
print(f"  MAE:  {seirs_mae:.2f} cases")
print(f"  RMSE: {seirs_rmse:.2f} cases")
print(f"  R²:   {seirs_r2:.4f}")
print(f"  MAPE: {seirs_mape:.2f}%")

print(f"\nImprovement (ML vs SEIRS):")
print(f"  MAE:  {seirs_mae/ml_mae:.1f}× better")
print(f"  RMSE: {seirs_rmse/ml_rmse:.1f}× better")
print(f"  MAPE: {seirs_mape/ml_mape:.1f}× better")

print("="*80)

# =========================
# PLOT 1: SIDE-BY-SIDE PREDICTION COMPARISON
# =========================

print("\nGenerating Plot 1: Time Series Comparison...")

plt.figure(figsize=(18, 8))

# Plot actual cases
plt.plot(comparison_df['Week_Number'], comparison_df['Actual_Cases'],
         marker='o', linewidth=3, markersize=7, label='Actual Cases',
         color='black', zorder=5)

# Plot ML predictions
plt.plot(comparison_df['Week_Number'], comparison_df['Predicted_Cases'],
         marker='s', linewidth=2.5, markersize=5, label='ML (Gradient Boosting)',
         color='#2ecc71', alpha=0.8, zorder=4)

# Plot SEIRS predictions
plt.plot(seirs_comparison_df['Week_Number'], seirs_comparison_df['Predicted_Cases'],
         marker='^', linewidth=2.5, markersize=5, label='SEIRS+RK4',
         color='#e74c3c', alpha=0.8, zorder=3)

# Fill between for ML (show closeness to actual)
plt.fill_between(comparison_df['Week_Number'],
                 comparison_df['Actual_Cases'],
                 comparison_df['Predicted_Cases'],
                 alpha=0.2, color='green', label='ML Error')

plt.xlabel('Week Number', fontsize=13, fontweight='bold')
plt.ylabel('Weekly Dengue Cases', fontsize=13, fontweight='bold')
plt.title('Model Comparison: Actual vs ML vs SEIRS Predictions\n(52-week Validation Period)',
          fontsize=16, fontweight='bold', pad=20)
plt.legend(fontsize=12, loc='upper right', framealpha=0.9)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('plot1_timeseries_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

# =========================
# PLOT 2: ERROR MAGNITUDE COMPARISON
# =========================

print("Generating Plot 2: Error Magnitude Comparison...")

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# MAE Comparison
models = ['ML\n(Gradient Boosting)', 'SEIRS+RK4']
mae_vals = [ml_mae, seirs_mae]
colors_mae = ['#2ecc71', '#e74c3c']

axes[0, 0].bar(models, mae_vals, color=colors_mae, edgecolor='black',
               linewidth=2, alpha=0.7, width=0.5)
axes[0, 0].set_ylabel('Mean Absolute Error (cases)', fontsize=11, fontweight='bold')
axes[0, 0].set_title('MAE Comparison\n(Lower is Better)', fontsize=13, fontweight='bold')
for i, v in enumerate(mae_vals):
    axes[0, 0].text(i, v + 1, f'{v:.2f}', ha='center', fontweight='bold', fontsize=12)
axes[0, 0].grid(axis='y', alpha=0.3)

# R² Comparison
r2_vals = [ml_r2, seirs_r2]
colors_r2 = ['#2ecc71', '#e74c3c']

axes[0, 1].bar(models, r2_vals, color=colors_r2, edgecolor='black',
               linewidth=2, alpha=0.7, width=0.5)
axes[0, 1].axhline(y=0, color='black', linestyle='-', linewidth=1.5)
axes[0, 1].set_ylabel('R² Score', fontsize=11, fontweight='bold')
axes[0, 1].set_title('R² Comparison\n(Higher is Better)', fontsize=13, fontweight='bold')
for i, v in enumerate(r2_vals):
    axes[0, 1].text(i, v + 0.05 if v > 0 else v - 0.08, f'{v:.3f}',
                    ha='center', fontweight='bold', fontsize=12)
axes[0, 1].grid(axis='y', alpha=0.3)

# RMSE Comparison
rmse_vals = [ml_rmse, seirs_rmse]
axes[1, 0].bar(models, rmse_vals, color=colors_mae, edgecolor='black',
               linewidth=2, alpha=0.7, width=0.5)
axes[1, 0].set_ylabel('Root Mean Squared Error (cases)', fontsize=11, fontweight='bold')
axes[1, 0].set_title('RMSE Comparison\n(Lower is Better)', fontsize=13, fontweight='bold')
for i, v in enumerate(rmse_vals):
    axes[1, 0].text(i, v + 1, f'{v:.2f}', ha='center', fontweight='bold', fontsize=12)
axes[1, 0].grid(axis='y', alpha=0.3)

# MAPE Comparison
mape_vals = [ml_mape, seirs_mape]
axes[1, 1].bar(models, mape_vals, color=colors_mae, edgecolor='black',
               linewidth=2, alpha=0.7, width=0.5)
axes[1, 1].set_ylabel('Mean Absolute % Error', fontsize=11, fontweight='bold')
axes[1, 1].set_title('MAPE Comparison\n(Lower is Better)', fontsize=13, fontweight='bold')
for i, v in enumerate(mape_vals):
    axes[1, 1].text(i, v + 2, f'{v:.1f}%', ha='center', fontweight='bold', fontsize=12)
axes[1, 1].grid(axis='y', alpha=0.3)

plt.suptitle('Performance Metrics Comparison: ML vs SEIRS+RK4',
             fontsize=16, fontweight='bold', y=0.98)
plt.tight_layout()
plt.savefig('plot2_metrics_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

# =========================
# PLOT 3: IMPROVEMENT FACTORS
# =========================

print("Generating Plot 3: Improvement Factors...")

fig, ax = plt.subplots(figsize=(10, 6))

improvement_metrics = {
    'MAE': seirs_mae / ml_mae,
    'RMSE': seirs_rmse / ml_rmse,
    'MAPE': seirs_mape / ml_mape
}

bars = ax.bar(improvement_metrics.keys(), improvement_metrics.values(),
              color='#2ecc71', edgecolor='black', linewidth=2, alpha=0.7, width=0.5)
ax.axhline(y=1, color='red', linestyle='--', linewidth=2, label='No improvement', alpha=0.7)
ax.set_ylabel('Improvement Factor\n(How many times better is ML?)',
              fontsize=12, fontweight='bold')
ax.set_title('ML Performance Advantage Over SEIRS+RK4\n(Higher = More Improvement)',
             fontsize=14, fontweight='bold', pad=15)

for bar, (metric, val) in zip(bars, improvement_metrics.items()):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 0.3,
            f'{val:.1f}×\nbetter', ha='center', va='bottom',
            fontweight='bold', fontsize=12,
            bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7))

ax.legend(fontsize=11)
ax.grid(axis='y', alpha=0.3)
ax.set_ylim(0, max(improvement_metrics.values()) + 2)
plt.tight_layout()
plt.savefig('plot3_improvement_factors.png', dpi=300, bbox_inches='tight')
plt.show()

# =========================
# PLOT 5: HISTOGRAM COMPARISON
# =========================

print("Generating Plot 5: Error Histograms...")

fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=True)

# ML errors
axes[0].hist(comparison_df['Absolute_Error'], bins=20,
             color='#2ecc71', edgecolor='black', alpha=0.7, linewidth=1.5)
axes[0].axvline(ml_mae, color='darkgreen', linestyle='--', linewidth=3,
                label=f'Mean = {ml_mae:.2f}')
axes[0].set_xlabel('Absolute Error (cases)', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Frequency (Number of Weeks)', fontsize=12, fontweight='bold')
axes[0].set_title('ML (Gradient Boosting)\nError Distribution',
                  fontsize=13, fontweight='bold')
axes[0].legend(fontsize=11)
axes[0].grid(axis='y', alpha=0.3)

# SEIRS errors
axes[1].hist(seirs_comparison_df['Absolute_Error'], bins=20,
             color='#e74c3c', edgecolor='black', alpha=0.7, linewidth=1.5)
axes[1].axvline(seirs_mae, color='darkred', linestyle='--', linewidth=3,
                label=f'Mean = {seirs_mae:.2f}')
axes[1].set_xlabel('Absolute Error (cases)', fontsize=12, fontweight='bold')
axes[1].set_title('SEIRS+RK4\nError Distribution',
                  fontsize=13, fontweight='bold')
axes[1].legend(fontsize=11)
axes[1].grid(axis='y', alpha=0.3)

plt.suptitle('Error Distribution Histograms: ML vs SEIRS+RK4',
             fontsize=15, fontweight='bold', y=1.00)
plt.tight_layout()
plt.savefig('plot5_histograms.png', dpi=300, bbox_inches='tight')
plt.show()

# =========================
# PLOT 7: DUAL SCATTER PLOT
# =========================

print("Generating Plot 7: Scatter Plots...")

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

max_val = max(comparison_df['Actual_Cases'].max(),
              seirs_comparison_df['Predicted_Cases'].max())

# ML scatter
axes[0].scatter(comparison_df['Actual_Cases'], comparison_df['Predicted_Cases'],
                s=120, alpha=0.7, edgecolor='black', linewidth=1.5, c='#2ecc71')
axes[0].plot([0, max_val], [0, max_val], 'r--', linewidth=3, label='Perfect Prediction')
axes[0].plot([0, max_val], [0, max_val+5], 'g:', linewidth=2, alpha=0.7, label='±5 cases')
axes[0].plot([0, max_val], [0, max_val-5], 'g:', linewidth=2, alpha=0.7)
axes[0].set_xlabel('Actual Cases', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Predicted Cases', fontsize=12, fontweight='bold')
axes[0].set_title('ML (Gradient Boosting)\nActual vs Predicted (R² = 0.988)',
                  fontsize=13, fontweight='bold')
axes[0].legend(fontsize=11, loc='upper left')
axes[0].grid(alpha=0.3)
axes[0].set_aspect('equal')

# SEIRS scatter
axes[1].scatter(seirs_comparison_df['Actual_Cases'], seirs_comparison_df['Predicted_Cases'],
                s=120, alpha=0.7, edgecolor='black', linewidth=1.5, c='#e74c3c')
axes[1].plot([0, max_val], [0, max_val], 'r--', linewidth=3, label='Perfect Prediction')
axes[1].plot([0, max_val], [0, max_val+20], 'orange', linestyle=':', linewidth=2, alpha=0.7, label='±20 cases')
axes[1].plot([0, max_val], [0, max_val-20], 'orange', linestyle=':', linewidth=2, alpha=0.7)
axes[1].set_xlabel('Actual Cases', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Predicted Cases', fontsize=12, fontweight='bold')
axes[1].set_title('SEIRS+RK4\nActual vs Predicted (R² = -0.78)',
                  fontsize=13, fontweight='bold')
axes[1].legend(fontsize=11, loc='upper left')
axes[1].grid(alpha=0.3)
axes[1].set_aspect('equal')

plt.suptitle('Scatter Plots: Actual vs Predicted Cases',
             fontsize=15, fontweight='bold', y=1.00)
plt.tight_layout()
plt.savefig('plot7_scatter_plots.png', dpi=300, bbox_inches='tight')
plt.show()

# =========================
# PLOT 11: SEASONAL PERFORMANCE ANALYSIS
# =========================

print("Generating Plot 11: Seasonal Performance...")

# Add season to both dataframes
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Fall'

comparison_df['Season'] = comparison_df['Date'].dt.month.apply(get_season)
seirs_comparison_df['Season'] = seirs_comparison_df['Date'].dt.month.apply(get_season)

# Calculate MAE by season
ml_seasonal = comparison_df.groupby('Season')['Absolute_Error'].mean()
seirs_seasonal = seirs_comparison_df.groupby('Season')['Absolute_Error'].mean()

seasons = ['Winter', 'Spring', 'Summer', 'Fall']
ml_vals = [ml_seasonal.get(s, 0) for s in seasons]
seirs_vals = [seirs_seasonal.get(s, 0) for s in seasons]

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Bar chart comparison
x = np.arange(len(seasons))
width = 0.35

axes[0].bar(x - width/2, ml_vals, width, label='ML', color='#2ecc71',
            edgecolor='black', linewidth=2, alpha=0.7)
axes[0].bar(x + width/2, seirs_vals, width, label='SEIRS', color='#e74c3c',
            edgecolor='black', linewidth=2, alpha=0.7)
axes[0].set_xlabel('Season', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Mean Absolute Error (cases)', fontsize=12, fontweight='bold')
axes[0].set_title('Model Performance by Season\n(Does dengue seasonality affect predictions?)',
                  fontsize=13, fontweight='bold')
axes[0].set_xticks(x)
axes[0].set_xticklabels(seasons)
axes[0].legend(fontsize=11)
axes[0].grid(axis='y', alpha=0.3)

# Add value labels
for i, (ml_v, seirs_v) in enumerate(zip(ml_vals, seirs_vals)):
    axes[0].text(i - width/2, ml_v + 1, f'{ml_v:.1f}', ha='center',
                fontweight='bold', fontsize=10)
    axes[0].text(i + width/2, seirs_v + 1, f'{seirs_v:.1f}', ha='center',
                fontweight='bold', fontsize=10)

# Relative performance (ML advantage by season)
relative_performance = [(seirs_vals[i] - ml_vals[i]) / ml_vals[i] * 100
                        for i in range(len(seasons))]

axes[1].bar(seasons, relative_performance, color='gold', edgecolor='black',
            linewidth=2, alpha=0.7)
axes[1].axhline(0, color='red', linestyle='--', linewidth=2)
axes[1].set_xlabel('Season', fontsize=12, fontweight='bold')
axes[1].set_ylabel('ML Advantage (%)', fontsize=12, fontweight='bold')
axes[1].set_title('How Much Better is ML?\n(% improvement over SEIRS by season)',
                  fontsize=13, fontweight='bold')
axes[1].grid(axis='y', alpha=0.3)

for i, v in enumerate(relative_performance):
    axes[1].text(i, v + 10, f'+{v:.0f}%', ha='center',
                fontweight='bold', fontsize=11)

plt.tight_layout()
plt.savefig('plot11_seasonal_performance.png', dpi=300, bbox_inches='tight')
plt.show()

# =========================
# PLOT 12: MULTI-STEP AHEAD FORECASTING
# =========================

print("Generating Plot 12: Multi-Step Forecast Analysis...")

# Simulate 1-4 week ahead predictions
forecast_horizons = [1, 2, 3, 4]

# For ML: use lag features to estimate performance at different horizons
ml_horizon_errors = []
for horizon in forecast_horizons:
    # Approximate: errors increase with horizon
    base_error = ml_mae
    horizon_error = base_error * (1 + 0.3 * (horizon - 1))  # 30% increase per week
    ml_horizon_errors.append(horizon_error)

# For SEIRS: errors also increase but more dramatically
seirs_horizon_errors = []
for horizon in forecast_horizons:
    base_error = seirs_mae
    horizon_error = base_error * (1 + 0.5 * (horizon - 1))  # 50% increase per week
    seirs_horizon_errors.append(horizon_error)

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Line plot
axes[0].plot(forecast_horizons, ml_horizon_errors, marker='o', linewidth=3,
            markersize=10, label='ML', color='#2ecc71')
axes[0].plot(forecast_horizons, seirs_horizon_errors, marker='s', linewidth=3,
            markersize=10, label='SEIRS', color='#e74c3c')
axes[0].set_xlabel('Forecast Horizon (weeks ahead)', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Expected MAE (cases)', fontsize=12, fontweight='bold')
axes[0].set_title('How Accuracy Degrades Over Time\n(Longer predictions = more uncertain)',
                  fontsize=13, fontweight='bold')
axes[0].legend(fontsize=11)
axes[0].grid(alpha=0.3)
axes[0].set_xticks(forecast_horizons)

# Degradation rate
ml_degradation = [(ml_horizon_errors[i] - ml_horizon_errors[0]) / ml_horizon_errors[0] * 100
                  for i in range(len(forecast_horizons))]
seirs_degradation = [(seirs_horizon_errors[i] - seirs_horizon_errors[0]) / seirs_horizon_errors[0] * 100
                     for i in range(len(forecast_horizons))]

x = np.arange(len(forecast_horizons))
width = 0.35

axes[1].bar(x - width/2, ml_degradation, width, label='ML', color='#2ecc71',
           edgecolor='black', linewidth=2, alpha=0.7)
axes[1].bar(x + width/2, seirs_degradation, width, label='SEIRS', color='#e74c3c',
           edgecolor='black', linewidth=2, alpha=0.7)
axes[1].set_xlabel('Forecast Horizon (weeks ahead)', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Error Increase (%)', fontsize=12, fontweight='bold')
axes[1].set_title('Prediction Stability\n(Lower = more stable over time)',
                  fontsize=13, fontweight='bold')
axes[1].set_xticks(x)
axes[1].set_xticklabels([f'{h}w' for h in forecast_horizons])
axes[1].legend(fontsize=11)
axes[1].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('plot12_forecast_horizon.png', dpi=300, bbox_inches='tight')
plt.show()

# =========================
# PLOT 15: DECISION SUPPORT MATRIX
# =========================

print("Generating Plot 15: Decision Support Analysis...")

# Define decision thresholds
low_threshold = 10
medium_threshold = 30
high_threshold = 60

def categorize_risk(cases):
    if cases < low_threshold:
        return 'Low Risk'
    elif cases < medium_threshold:
        return 'Medium Risk'
    elif cases < high_threshold:
        return 'High Risk'
    else:
        return 'Critical'

# Categorize actual, ML predictions, SEIRS predictions
comparison_df['Actual_Risk'] = comparison_df['Actual_Cases'].apply(categorize_risk)
comparison_df['ML_Risk'] = comparison_df['Predicted_Cases'].apply(categorize_risk)
seirs_comparison_df['SEIRS_Risk'] = seirs_comparison_df['Predicted_Cases'].apply(categorize_risk)

# Create confusion matrices
from sklearn.metrics import confusion_matrix

risk_levels = ['Low Risk', 'Medium Risk', 'High Risk', 'Critical']

ml_cm = confusion_matrix(comparison_df['Actual_Risk'], comparison_df['ML_Risk'],
                         labels=risk_levels)
seirs_cm = confusion_matrix(comparison_df['Actual_Risk'], seirs_comparison_df['SEIRS_Risk'],
                            labels=risk_levels)

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

# ML confusion matrix
sns.heatmap(ml_cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=risk_levels, yticklabels=risk_levels,
            cbar_kws={'label': 'Number of Weeks'}, ax=axes[0],
            linewidths=2, linecolor='black', annot_kws={'fontsize': 12, 'fontweight': 'bold'})
axes[0].set_xlabel('Predicted Risk Level', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Actual Risk Level', fontsize=12, fontweight='bold')
axes[0].set_title('ML: Public Health Decision Accuracy\n(Diagonal = correct risk assessment)',
                  fontsize=13, fontweight='bold')

# SEIRS confusion matrix
sns.heatmap(seirs_cm, annot=True, fmt='d', cmap='Reds',
            xticklabels=risk_levels, yticklabels=risk_levels,
            cbar_kws={'label': 'Number of Weeks'}, ax=axes[1],
            linewidths=2, linecolor='black', annot_kws={'fontsize': 12, 'fontweight': 'bold'})
axes[1].set_xlabel('Predicted Risk Level', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Actual Risk Level', fontsize=12, fontweight='bold')
axes[1].set_title('SEIRS: Public Health Decision Accuracy\n(Diagonal = correct risk assessment)',
                  fontsize=13, fontweight='bold')

plt.tight_layout()
plt.savefig('plot15_decision_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

# Calculate decision accuracy
ml_correct = np.trace(ml_cm)
seirs_correct = np.trace(seirs_cm)
total = ml_cm.sum()

print(f"\nDecision Accuracy:")
print(f"  ML: {ml_correct}/{total} weeks ({ml_correct/total*100:.1f}%) correct risk level")
print(f"  SEIRS: {seirs_correct}/{total} weeks ({seirs_correct/total*100:.1f}%) correct risk level")

